### ISSUE TITLE
Armada needs a public synchronous (chat) communications platform

### ISSUE THREAD

**Issue by jayofdoom** [G-Research/armada#1024]
As Armada will be growing in contributor and user base, we should consider how to enable good communications between G-Research based contributors and contributors outside of the organization.

I did some research about how CNCF projects communicate, as a potential template for us to follow as a project that has applied for incubation(1). Of the 33 projects listed as incubating on the CNCF website; all but one have an easily found chat method.

The vast majority of those use slack for communication, with others using IRC, Discord, and Gitter. Some projects have their own Slack servers, but most use the CNCF slack (cloud-native.slack.com with signups via slack.cncf.io).

Given, to my understanding, most developers currently working on this project are active in some Slack servers, using Slack seems like the logical solution.

I propose we agree to use a public Slack environment to communicate about Armada technical decisions and to allow a place for potential new users and contributors to collaborate with us. If we come to this agreement, I can reach out to the teams that run CNCF slack if they'd be willing to host a channel about Armada, in order to make it simple for us to create the channel without having to lure folks to a new Slack server.

What do you all think?

1: https://docs.google.com/spreadsheets/d/1gDG8AKDouxDu94sgQccR6zhIkezO11eQXlhrg7XhG8w

**Comment by jayofdoom** [comment]
@rankindaveyg @stackedsax @c-rindi As we talked about in Armada outreach, this is a logical next step for setting up Armada to be a more open community.

**Comment by rankindaveyg** [comment]
This looks great, ship it!

**Comment by c-rindi** [comment]
Thanks for the suggestion, @jayofdoom. Those both sound like a great place to enable communications. 
In the meantime, people can continue to chat on the underused Discussions section [here](https://github.com/G-Research/armada/discussions).
🤞🏾the CNCF/Cloud Native folks let us in. 😉

**Comment by stackedsax** [comment]
suepr weird, I wrote a response, but it never made it here?

**Comment by dgl** [comment]
Just to clarify the two links lead to the same place -- slack.cncf.io is the signup link for cloud-native.slack.com. But the CNCF slack sounds like a good place.

**Comment by stackedsax** [comment]
@jayofdoom, nono, just took me a sec to find the email that never went through.  Here were my thoughts:

- Just to be pedantic, we've applied to Sandbox of the CNCF not Incubation yet.  But sandbox status gives us the same rights to create a room in [cloud-native.slack.com](http://cloud-native.slack.com/).  I confirmed this the other day.
- It might be hard (impossible?) for Chris and Albin to communicate in the future #armada channel on the cncf workspace.  We could, perhaps, create a Slack connect room to connect them into the cncf workspace, but that needs to be a private room for the GR admins to approve it. But that doesn't feel like what we want to encourage conversation with the general public.  @severinson @d80tb7, are you able to communicate on any public slack channels while you're at work?  If so, what's the process?
- I think you clarified a bit more in #1044, but I just want to understand the full breadth of the type of communication you envision happening on this channel.  I've seen some projects just use these rooms to interact with people external to the core development team, but I think I'd prefer any and all development chat conversation to happen here.  In other words, moving the entire dev conversation from the gr-oss workspace and the internal GR slack channel over to the cncf workspace.  I feel like that was what you were proposing, too, I just wanted to confirm.
- For other projects, I'm fine with opening up the gr-oss workspace as a place where we can invite all community members to join us, but probably the cncf workspace is better for more cncf-related eyeballs.

Again, I'm all for this, overall.  The details around collaboration with the internal GR team are the only big question mark I have.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1024?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by stackedsax** [comment]
Heya,

Yep, I’d like us to move to something more public. Some thoughts:

   1. We've applied to Sandbox of the CNCF not Incubation yet.  But sandbox
   status gives us the same rights to create a room in
   cloud-native.slack.com.
   2. I think slack.cncf.io is is just a shortcut to get an invite to
   cloud-native.slack.com.  They should be the same thing at the end of the
   day.
   3. It might be hard (impossible?) for Chris and Albin to communicate in
   the future #armada channel on the cncf workspace.  We could, perhaps,
   create a Slack connect room to connect them into the cncf workspace, but
   that needs to be a private room for the GR admins to approve it.  Sadly,
   this isn't exactly what we want for the general public.  Chris and Albin
   could, potentially, return home every time they want to send a Slack
   message?
   4. Can you be clearer here about the type of communication you envision
   happening on this channel?  I've seen some projects just use these rooms to
   interact with people external to the core development team, but I think I'd
   prefer any and all development chat conversation to happen here.  In other
   words, moving the dev conversation from the gr-oss workspace to the cncf
   workspace.  I feel like that was what you were proposing, too.
   5. There's a piece of me that kinda wants to open up the gr-oss
   workspace as a place where we can invite all community members to join us,
   but probably the cncf workspace is better for more cncf-related eyeballs.

Again, I'm all for this, overall.

-Alex
