### ISSUE TITLE
Armada clients should use keepalive

### ISSUE THREAD

**Issue by rankindaveyg** [G-Research/armada#1026]
See ARMADA-1099.

We've seen some issues around load balanacer instability. Ensure the go/dotnet/python clients make use of grpc keepalive.

**Comment by kannon92** [comment]
Researching this, it seems that this is trivially supported in the python client.  GRPC keepalive is typically used as an channel parameters. 

A user of the client can add keepalive via:

```
tester = ArmadaClient(
    grpc.insecure_channel(target="127.0.0.1:50051", options={
        'grpc.keepalive_time_ms': 30000,
    }.items(),)
)
```

**Comment by d80tb7** [comment]
I think we might also need to set (or at least expose in config) some setting on the server.  See https://github.com/grpc/grpc/blob/master/doc/keepalive.md

**Comment by kannon92** [comment]
Ah.  I see.  I read this ticket as "Keep Alive is already included in the server".  We just need the client to use these settings.  

Yea, we should add confg settings to armada server for keep alive

**Comment by d80tb7** [comment]
Yeah- tbf it wasn't entirely clear what the scope of this issue was.  I've raised #1094 to expose the relevant keepalive parameters via server config
