### ISSUE TITLE
npm audit shows many vulnerabilities

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1058]
When you run `npm audit`, you can see a series of package vuleriabilites.

```
found 63 vulnerabilities (2 low, 17 moderate, 26 high, 18 critical)
```

We should remove these vulnerabilities.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1058?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by kannon92** [comment]
We decided to not go through with this.
