### ISSUE TITLE
Lack of infomation in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Sharpz7** [G-Research/armada#1131]
It would be cool to have more infomation included in the contributing guide:

- Branch naming schemes 
- How to go from issue to code merge (i.e step-by-step guide of the steps you would want new contributors to follow)
- Doing some commit cleanup (i.e squash all fixups and fixup-type commits)

**Comment by kannon92** [comment]
One more thing to add is that the names of the branch must follow proper docker names

> A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.

**Comment by Sharpz7** [comment]
Thanks! I will start working on a draft of a new file after I get a couple of example files written for the python client ;)
