### ISSUE TITLE
Adding subscribe of events to JobService

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1138]
A major part of our JobService is to not poll for events but to use pub/sub.  We will use this in our JobServer cache.

**Comment by kannon92** [comment]
https://github.com/G-Research/armada/issues/1138 is being merged into this issue.

**Comment by rankindaveyg** [comment]
21

**Comment by kannon92** [comment]
Closing due to issue being too large.  Broke up into two different issues: https://github.com/G-Research/armada/issues/1265 and https://github.com/G-Research/armada/issues/1264
