### ISSUE TITLE
SPIKE: Gogo protobuf is no longer maintained - investigate alternatives

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1139]
https://github.com/gogo/protobuf

If you go to the gogo/protobuf  github page, there is a request to find new maintainers for this project.  

We depend on this for our APIs so we should maybe look for alternatives.

**Comment by kannon92** [comment]
Some projects that could be useful: https://github.com/CrowdStrike/csproto

**Comment by kannon92** [comment]
From @severinson 

> Perhaps you can create a ticket to investigate long-term proto options for Armada?

Whoever pulls this PR should do some research into options

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1139?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by severinson** [comment]
This isn't a priority. I'm closing the ticket. If it becomes important in the future, we can re-open it.
