### ISSUE TITLE
Update minimum supported Go version from 1.16

### ISSUE THREAD

**Issue by jayofdoom** [G-Research/armada#1142]
This is a tracking issue to track various issues we're having regarding continued support of Go 1.16. It may not be the time to make the change now, but we should ensure we're documenting the tradeoffs we're making.

- We are locked into our current versions of `k8s.io/component-helpers`, `k8s.io/apimachinery` and `k8s.io/client-go`, newer versions do not support Go 1.16.
  - Related PRs: #1097 #1096 #1095 #1135
- Go 1.16 is losing security support when Go 1.19 is released. This is scheduled for August 2022 (https://tip.golang.org/doc/go1.19)

**Comment by jayofdoom** [comment]
We've preliminarily agreed to move to Go 1.18.3.

**Comment by jayofdoom** [comment]
As part of this, a nice to have would be some documentation around:
- Where and why we pin versions for CI (we will pin to a patch version)
- How we perform go version upgrades (for minor or patch versions)

**Comment by jayofdoom** [comment]
So, I'm going to write a small doc on changing golang versions, but the reality is this is mostly trivial to push a button on when G-R is ready.

Originally, I was thinking we'd publish separate artifacts -- one for old (1.16) go  and one for newer (1.18) go -- but that doesn't make sense for a compiled application like it does for python.

The output of this issue then, before I table it for later is:
- a PR upgrading to Go 1.18 when we're ready, that includes a small doc (or really, probably just comments in the makefile) about how/where to change the go version we build against
- an email to stakeholders running this in production, letting them know that PR exists, and that we're ready to merge it at will

This work should be complete by EOD tomorrow as long as there's no controversy about how to do this.

**Comment by kannon92** [comment]
https://github.com/G-Research/armada/pull/1258 closes this issue.
