### ISSUE TITLE
Clicking on annotation link in lookout should open a new tab 

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1144]
It would be better if the links opened in a new tab, rather than replacing lookout.

_Originally posted by @robertdavidsmith in https://github.com/G-Research/armada/issues/701#issuecomment-1171469338_

When a user clicks on a link in annotations, the browser should open a new tab rather than overwriting the existing tab.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1144?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by kannon92** [comment]
We can close with https://github.com/G-Research/armada/pull/1421
