### ISSUE TITLE
Write python example scripts and add Documentaition

### ISSUE THREAD

**Issue by Sharpz7** [G-Research/armada#1146]
Create 4 example python scripts:

- queue.py covering queue code
- jobs.py covering basic jobs code
- monitor.py covering how to monitor jobs and jobsets
- priority.py covering how to change the priority of a job.

Also create a README within an examples folder with more infomation, like what is done [here](https://github.com/zenml-io/zenml/tree/main/examples)

**Comment by richscott** [comment]
Also examples of:
- canceling jobs
- using job sets
