### ISSUE TITLE
Documentation for the Airflow Operator

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1173]
We should have a quick description of how to test the airflow operator, how to run a simple airflow instance and how to test the Armada Airflow Operator.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1173?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by kannon92** [comment]
Chatting with Adam Pitt.  We will make this a bit simpler.  We will focus on a README.md on building the airflow operator and testing.  

Airflow Integration will be a followup.  Airflow integration is a pain and it is changes based on how you set up your executors.
