### ISSUE TITLE
Helm chart for the job service

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1174]
We should create a helm chart for the job service so we can deploy into kubernetes.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1174?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott
