### ISSUE TITLE
Use a custom auto-generated typing class to add good docs to the python client

### ISSUE THREAD

**Issue by Sharpz7** [G-Research/armada#1187]
The idea is the run a tox command, that:

- Reads the .proto file comments, types etc and generate a `typings.py` file with descriptions of each type. The comments in the .proto files can include links to relavent docs.
- These types would not be truly connected to the grpc generated files, but instead be user readable, created to the standards we use in our codebase. 
- The types could then be implemented into `client.py` to give extra infomation.

**Comment by jayofdoom** [comment]
Is the idea here to write a G-R/armada bespoke tool to do this? Or do you have a library in mind? 

I like the proposed end result, but there are potentially two problems with this route:
- Maintenance cost of maintaining this generation
- If we do this for python, must we do it for C#? For other languages we eventually write clients for?

IMO it may just not be sustainable. WDYT?

**Comment by Sharpz7** [comment]
Yeah I do not currently know a program that can do this, but I will research it. I honestly could build a tool myself that can handle it, but idk if that is something you guys would be comfertable with?

And this would just be for python. Python and GRPC do really not gel well together, where as in C# it is a fair bit more readable.

**Comment by jayofdoom** [comment]
I would be very concerned about the cost/benefit ratio if it's something built bespoke for this project that we had to maintain long term. It's very possible others will disagree :)

**Comment by Sharpz7** [comment]
After looking, I found this https://github.com/protocolbuffers/protobuf/issues/2638#issuecomment-1106725624
I think we can use `.pyi` files since grpc supports them. Kevin actually mentioned this issue as well

**Comment by Sharpz7** [comment]
This would be needed less if #1192 and #1194 are implemented

**Comment by Sharpz7** [comment]
https://github.com/nipunn1313/mypy-protobuf Seems to add a valid solution.
