### ISSUE TITLE
Return custom objects from Armada Python Client

### ISSUE THREAD

**Issue by Sharpz7** [G-Research/armada#1192]
This would make it easier to document these returned objects, and make the infomation easier to collect. I think this makes sense as gRPC is implemented differently for each language, so we might as well make the client more user-friendly since gRPC in python is a bit of a mess.

(**Note: I would make sure the original response is included in this custom response so if something is added in the future / some complicated behavior is needed this can still be used**)

The custom reponse objects would include:

- The default .proto file infomation (To make this process easier since it will be properly documented)
```py
    while True:
        info1 = client.get_queue_info(name=queue)
        info2 = client.get_queue(name=queue)

        if last_info1 is None:
            last_info1 = info1
            last_info2 = info2

        # With Custom Responses, that are documented, this would autocomplete instead of having to be done with trial and error.
        if last_info2.priority_factor != info2.priority_factor:
            print(
                f"Priority factor changed from {last_info2.priority_factor} to {info2.priority_factor}"
            )

        for new, old in zip(info1.active_job_sets, last_info1.active_job_sets):
            if new.leased_jobs != old.leased_jobs:
                print(
                    f"Leased jobs changed from {old.leased_jobs} to {new.leased_jobs}"
                )

        last_info1 = info1
        last_info2 = info2

        time.sleep(0.2)
```

- Any errors attached to the response (instead of doing try/except
```py

# This is a lot of extra code when the client could handle it
try:
    client.create_queue(name=queue, priority_factor=1)
except grpc.RpcError as e:
    code = e.code()
    if code == grpc.StatusCode.ALREADY_EXISTS:
        print(f"Queue {queue} already exists")
        client.update_queue(name=queue, priority_factor=1)
    else:
        raise e
```

- If the response is an event stream, un-nest the data to make it easy to determine the event type (Instead of having to do this workaround)

```py
# This code is a work around so that all events on a job can be watched, and only the relavent pieces of infomation are returned.
# Because of how the .proto files are layed out, this is quite difficult though.


def useful_message(message, queue):

    acceptable = [
        (message.running, "Running"),
        (message.succeeded, "Succeeded"),
        (message.failed, "Failed"),
        (message.reprioritizing, "Reprioritizing"),
        (message.failed, "Failed"),
        (message.cancelled, "Cancelled"),
        (message.cancelling, "Cancelling"),
        (message.reprioritized, "Reprioritized"),
        (message.reprioritizing, "Reprioritizing"),
        (message.queued, "Queued"),
    ]

    for accepted, msg_type in acceptable:
        if accepted.queue == queue:
            return accepted, msg_type, True

    return None, None, False


def watch_job_set(client: ArmadaClient, queue: str, job_set_id):
    attempts = 0

    while True:
        try:
            event_stream = client.get_job_events_stream(
                queue=queue, job_set_id=job_set_id
            )
            for event in event_stream:
                msg, msg_type, useful = useful_message(event.message, queue)
                if useful:
                    print(msg_type, ":", msg.job_id)

        except grpc.RpcError as e:
            # not found
            if e.code() != grpc.StatusCode.NOT_FOUND:
                print("Unexpected error:", e)
                exit()

        attempts += 1
        time.sleep(1)

        if attempts > 10:
            print("Exiting - too many attempts")
            exit()
```
- Using this example code (By intergrating it into this reponse object, all responses could have a `wait for succeseed ` method, that would do the same as the following code

```py
def wait_for_job_event(event_stream, job_id, event_type):
    for event in event_stream:
        if job_id == event.message.succeeded.job_id and event_type == "SUCCEEDED":
            return True

        elif job_id == event.message.running.job_id and event_type == "RUNNING":
            return True

        elif (
            job_id == event.message.reprioritizing.job_id
            and event_type == "REPRIORITIZING"
        ):
            return True

        elif (
            job_id == event.message.reprioritized.job_id
            and event_type == "REPRIORITIZED"
        ):
            return True

        elif job_id == event.message.failed.job_id and event_type == "FAILED":
            return True

        elif job_id == event.message.cancelled.job_id and event_type == "CANCELLED":
            return True

        elif job_id == event.message.cancelling.job_id and event_type == "CANCELLING":
            return True

        elif job_id == event.message.queued.job_id and event_type == "QUEUED":
            return True

    return False
```

**Comment by kannon92** [comment]
So IMO, we should add this functionality to the proto definitions rather than generating them in new language.  We would like to generate grpc clients for Java, Python and C#.  I think its not really scalable for us to add these things in each language we want to support.   

```
        # With Custom Responses, that are documented, this would autocomplete instead of having to be done with trial and error.
        if last_info2.priority_factor != info2.priority_factor:
            print(
                f"Priority factor changed from {last_info2.priority_factor} to {info2.priority_factor}"
            )

        for new, old in zip(info1.active_job_sets, last_info1.active_job_sets):
            if new.leased_jobs != old.leased_jobs:
                print(
                    f"Leased jobs changed from {old.leased_jobs} to {new.leased_jobs}"
                )
```

I don't really understand this.  Are you saying you want typing of these objects so you can use them in IDE?  I think that we should look into options for typing of python protobuf [mypy-protobuf](https://github.com/nipunn1313/mypy-protobuf).  But this is pretty standard in protobuf so you can usually read the proto definition and see what members are availble to the payload.    


                
```
# This is a lot of extra code when the client could handle it
try:
    client.create_queue(name=queue, priority_factor=1)
except grpc.RpcError as e:
    code = e.code()
    if code == grpc.StatusCode.ALREADY_EXISTS:
        print(f"Queue {queue} already exists")
        client.update_queue(name=queue, priority_factor=1)
    else:
        raise e
```

What you are suggesting is that our rpc calls should probably return error messages as part of the rpc call.  

```
    rpc CreateQueue (Queue) returns (google.protobuf.Empty) {
        option (google.api.http) = {
            post: "/v1/queue"
            body: "*"
        };
    }
    rpc UpdateQueue (Queue) returns (google.protobuf.Empty) {
        option (google.api.http) = {
            put: "/v1/queue/{name}"
            body: "*"
        };
    }
    rpc DeleteQueue (QueueDeleteRequest) returns (google.protobuf.Empty) {
        option (google.api.http) = {
            delete: "/v1/queue/{name}"
        };
    }

```

These calls that return empty are difficult to deduce error.  I think we can ask GR if we can update the API to have corresponds responses for these in cases of errors.  No guarantee though.

> If the response is an event stream, un-nest the data to make it easy to determine the event type (Instead of having to do this workaround)

I think this is a good idea to add to python client.  I think the oneof proto functionality isn't as clean as other languages so it is quite a pain to work with.  The Go code does have some utilities to make working with events simpler.    

> Using this example code (By intergrating it into this reponse object, all responses could have a wait for succeseed method, that would do the same as the following code

I added a similar idea in the client for my airflow operator.  It wasn't a favorable change so I think we don't want to encourage watch events for a single jobid.  Armada was designed to watch an entire job-set and have the user be notified of changes.  We don't want to encourage polling of a job-set for a single job id.  

I am trying to implement this right now in my Airflow work because this is super useful but it goes against how Armada was designed.

**Comment by richscott** [comment]
> You do think creating flattening the event response type is a good idea - how would you want to see this
> implemented? (Maybe as another method called process_event or just configure the event stream method better?

I like the idea of a `process_event()` utility - but maybe something more descriptive than "process"?  Would something like `flatten_event_response()` or `unmarshal_event_response()` be better?

Re adding to the API - yes, I'd suggest just making a new issue, so we have something trackable for discussions with GR and others.

**Comment by Sharpz7** [comment]
> > You do think creating flattening the event response type is a good idea - how would you want to see this
> > implemented? (Maybe as another method called process_event or just configure the event stream method better?
> 
> I like the idea of a `process_event()` utility - but maybe something more descriptive than "process"? Would something like `flatten_event_response()` or `unmarshal_event_response()` be better?
> 
> Re adding to the API - yes, I'd suggest just making a new issue, so we have something trackable for discussions with GR and others.

Cool! I shall make 2 new issues, one for this event utility, and one for the new responses for the queue grpc calls

**Comment by richscott** [comment]
> I shall make 2 new issues, one for this event utility, and one for the new responses for the queue grpc calls

👍🏼

**Comment by Sharpz7** [comment]
Created https://github.com/G-Research/armada/issues/1198 and https://github.com/G-Research/armada/issues/1199
