### ISSUE TITLE
Add Richer Docstrings to make the website docs nicer

### ISSUE THREAD

**Issue by Sharpz7** [G-Research/armada#1193]
Add example usage code to docstrings of the python client.

This will make the online documentaition generation look a lot better. Would be interesting to see if markdown is supported, then that could look significantly better.

**Comment by Sharpz7** [comment]
Will be delayed until after https://github.com/G-Research/armada/issues/1147

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1193?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott
