### ISSUE TITLE
Remove all kwargs usage from client.py

### ISSUE THREAD

**Issue by Sharpz7** [G-Research/armada#1194]
Instead of using `**query_params` and `**job_item_params`, we should just add all the custom types that both support based on the .proto files. For example this python example, where the PodSpec object is reference [here](https://github.com/G-Research/armada/blob/e4c4495c6f3605bef87af3111e2187eb1dda2a76/pkg/api/submit.proto#L21).

This could be done for the rest of the `JobSubmitRequestItem` prototype as well as all other methods within `client.py`

```py
  def create_job_request_item(
      self, pod_spec: core_v1.PodSpec, priority: int = 1, **job_item_params
  ):
```
(Referenced from [client.py](https://github.com/G-Research/armada/blob/9eeeab70167c2d6ee7f0f60c7256b7c8ee7736e4/client/python/armada_client/client.py#L217))

**Comment by Sharpz7** [comment]
Will be delayed until after https://github.com/G-Research/armada/issues/1147

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1194?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott
