### ISSUE TITLE
Event Processing / Flattening Method

### ISSUE THREAD

**Issue by Sharpz7** [G-Research/armada#1198]
Create a new method in the python client, something like `unmarshal_event_response`, to make it easier to access event data.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1198?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott
