### ISSUE TITLE
Add an issue and PR template 

### ISSUE THREAD

**Issue by stackedsax** [G-Research/armada#1201]
I think it would be useful for us to add an issue and PR template to this repo, especially if we want to encourage potential community members to contribute.

@mfkl, I know you have opinions here if you want to opine and give some suggestions. I think you've helped set up some templates in some of our other repo's.  Likewise, @pavlovic-ivan.  @jayofdoom, you have any guidelines you like to follow here?

**Comment by pavlovic-ivan** [comment]
Hi Alex, thanks for reaching out. I would suggest using Github forms for this purpose. They give us the ability to create actual input fields with validation. Thus we can force a user to input data we can't go without

**Comment by stackedsax** [comment]
Yep, I think we have a few examples from other projects that we could just apply here, yes?

**Comment by pavlovic-ivan** [comment]
Correct :)

**Comment by mfkl** [comment]
> I know you have opinions here if you want to opine and give some suggestions.

Yes. Most important in my experience is to require a git-hosted [mcve](https://stackoverflow.com/help/minimal-reproducible-example) repro from the user. This saves a lot of time and headache in the long run for maintainers, by being able to just clone and run a minimal reproducible example. 

For other issue template examples, I think the consul project has a good one https://github.com/G-Research/consuldotnet/blob/master/.github/ISSUE_TEMPLATE/bug_report_form.yaml.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1201?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott
