### ISSUE TITLE
Simplify Golang unwrapping function

### ISSUE THREAD

**Issue by Sharpz7** [G-Research/armada#1204]
Can be found here:

* https://github.com/G-Research/armada/blob/master/pkg/api/event_util.go#L34

This is basically suggesting we do what I did in the Python client, using:
```py
msg_type = event.message.WhichOneof("events")
message = getattr(event.message, msg_type)
```

This in theory could be done in Golang, since the `WhichOneof` is a property of googles protobuf, and we can access attributes at runtime using https://pkg.go.dev/github.com/ssrathi/go-attr

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1204?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by Sharpz7** [comment]
After looking into this more, it seems that the golang code does not include an equivalent to `WhichOneOf` to conform to the expected programming standards within golang. I think this issue should be closed
