### ISSUE TITLE
Propose a set of linters for Armada

### ISSUE THREAD

**Issue by dejanzele** [G-Research/armada#1208]

**Comment by kannon92** [comment]
Is this related https://github.com/G-Research/armada/issues/659?

**Comment by dejanzele** [comment]
My recomendation for running lint pass would be to use [golangci-lint](https://github.com/golangci/golangci-lint) - 

My recomendation would be to use the following linters in Armada:
* [gofumpt](https://github.com/mvdan/gofumpt) - linter on common Golang coding conventions
* [lll](https://github.com/walle/lll) - linter for long lines
* [go-critic](https://github.com/go-critic/go-critic) - static code analysis for bugs
* [staticcheck](https://github.com/dominikh/go-tools/tree/master/cmd/staticcheck) - amazing static code analysis, code simplification, bugs

Here is a nice post on amazing Golang linters - https://github.com/golangci/awesome-go-linters

**Comment by dave-gantenbein** [comment]
This one is interesting: https://github.com/lafolle/flen

**Comment by kannon92** [comment]
https://github.com/G-Research/armada/pull/1362

We can close as this is complete.  This is a WIP as we have a lot of failures if we include linters.
