### ISSUE TITLE
Improve Armada Executor logs to print more available resources

### ISSUE THREAD

**Issue by dejanzele** [G-Research/armada#1218]

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1218?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by dejanzele** [comment]
Executor already has metrics on which resources are available (gpu, ephemeral-storage).
Improve Executor logs to log gpu and ephemeral storage availability
