### ISSUE TITLE
Create new contributing file for the python client 

### ISSUE THREAD

**Issue by kindyluv** [G-Research/armada#1234]
Inclusions are:

1) Add easy installation procedures for Linux OS
2) Add easy installation procedures for Mac OS
3) Add easy installation procedures for Windows OS
4) Add links to the [library.md](https://armadaproject.io/libraries)

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1234?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott
