### ISSUE TITLE
Spike: get the client code out of the monorepo

### ISSUE THREAD

**Issue by dave-gantenbein** [G-Research/armada#1244]

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1244?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by jayofdoom** [comment]
There has been an edict that the .proto files will remain in the repo as part of this step of the migration.

**Comment by dave-gantenbein** [comment]
Final output: a plan of action with tickets written for how we'll proceed.

**Comment by jayofdoom** [comment]
I have a strong preference that we do this without loss of any git history. I know how to do this if you wanna reach out.

**Comment by kannon92** [comment]
Our team has discussed this internally.  It does not seem like this work is likely to occur if we aren’t able to remove the API from the repo.  If we want to get the client code out of the monorepo, we really should discuss how to version our API as we need to test if any API change will break the existing clients.

We would be willing to discuss this more if we can host the Armada API in a separate repo.  This allows us to version our API and python/C# can import these projects as needed.  However, this does mean that any API update will require a PR that only changes the API.  And then a API for each change in the client repos.  Is this a Developer Experience that GR would be happy with?

The other issue is that the amount of development in the clients is very small so it does not seem that the development effort to create a distributed repo ecosystem is worth it.  To be clear, we are talking about toolchains that open up automated PR if the API changes in 2 languages (as of today).  We need to figure out how to write integrations tests by importing the entire Armada application.  There is also the process of reconcile releases of Armada with the various clients.  In addition to the points above, it will also cause developers to take more time to build clients and release new API.  (1 PR goes to at least 3-4 PRs) [Armada -> C#, python, airflow]
