### ISSUE TITLE
SPIKE: investigate Volcano integration

### ISSUE THREAD

**Issue by dave-gantenbein** [G-Research/armada#1249]
Can we potentially leverage its existing integrations rather than hand rolling all of them ourselves?

**Comment by kannon92** [comment]
I believe that @carlocamurri may have done some research into this.  May benefit us to discuss findings before someone starts.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1249?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott
