### ISSUE TITLE
Document+perform manual docker image creation w/inital upload

### ISSUE THREAD

**Issue by jayofdoom** [G-Research/armada#1272]
This ticket is complete when:
- documentation around name/versioning schemes for our docker images exist
- the first release of these images have been pushed to a dockerhub repo, with the manual process used to push them documented

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1272?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott
