### ISSUE TITLE
Add a new field to JobStatus that tells about connection status

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1280]
Currently, we have no way to determine if there is a connection issue in JobService/Airflow Operator.  

Some areas of interest can be a connection issue that causes us to lose connection to the event subscription.  

A proposal is to add a new field to the jobservice proto that can reflect what errors we had.  

For example, if we are unable to connect to the Event Client, a job status could still be achieved since it is in the database.  But the connection is unhealthy so we could potentially never get updates to the cache.  

We should report if there are issues such as this.    

Work needed:

1) Add a new field to the jobservice api definition.
2) Add ways for job service to report these errors in the jobservice code (golang)
3) Log this message in the airflow operator.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1280?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott
