### ISSUE TITLE
Add retry connection ability to the jobservice 

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1281]
The jobservice will connect to Armada via the EventClient.  There will be connection issues so we should handle reconnection in this service.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1281?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott
