### ISSUE TITLE
Start using pycoverage

### ISSUE THREAD

**Issue by Sharpz7** [G-Research/armada#1283]
[pycoverage](https://coverage.readthedocs.io/en/6.4.2/) is a tool that allows you to view at a glance how much of the python code is covered by tests. It will be useful to gauge how much effort needs to be put to writing new unit tests in the future.

**Comment by Sharpz7** [comment]
I think we would likely want to do something like this https://github.com/codecov/example-python.

@jayofdoom would it be possible to get this setup? Would need something like [codecov.io](https://about.codecov.io/) to have access to the repo.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1283?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott
