### ISSUE TITLE
Start using sphinx_toolbox for autodocumentaition

### ISSUE THREAD

**Issue by Sharpz7** [G-Research/armada#1284]
`sphinx_toolbox` adds a bunch of extra extentions that allow for better behavior with `sphinx_jekyll_builder`:

- sphinx_toolbox.more_autodoc.autonamedtuple: Will allow for better docs for the named tuple we use since https://github.com/G-Research/armada/pull/1266.

- In general, using this tool also correctly makes all module paths full. What I mean by this is instead of
```
* **job_request_items** – List[JobSubmitRequestItem]
```
 We would have
 ```
* **job_request_items** – List[armada_client.armada.submit_pb2.JobSubmitRequestItem]
```

This would in my opinion be better for docs as it will make it clearer where a type is coming from, epescially in cases where there are two types that are spelt the same but come from difference packages.

**Comment by jayofdoom** [comment]
Sounds sane to me. Do it?
