### ISSUE TITLE
Include a swagger UI page for our APIs

### ISSUE THREAD

**Issue by JamesMurkin** [G-Research/armada#1292]
Currently we only generate a swagger.json that we expose on our apis.

However it'd be nice if we also exposed a full swagger UI - https://swagger.io/tools/swagger-ui/

So that users can see and interact with it from the webpage more easily

**Comment by kannon92** [comment]
Is there still an interest in keeping the REST API for this once we migrate our client code to GRPC?  

I really like swagger-ui but I thought that we were aiming to phase out REST based APIs?

**Comment by JamesMurkin** [comment]
That is a totally fair comment, I think its a bit undecided. If we do choose to go that route, then this ticket would indeed be irrelevant

We should discuss what we want to do about REST and GRPC going forward

However if we do keep REST in any capacity, I don't think we'd want a swagger UI - as our users internally would very much appreciate it

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1292?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott
