### ISSUE TITLE
improving Contributing guide

### ISSUE THREAD

**Issue by dans77777** [G-Research/armada#1302]
I saw some good description related to the issues and pull request is missing . I will try to improve this .

**Comment by c-rindi** [comment]
Thank you, @dans77777. 
Can you please give some more details as to the improvements to be made?

**Comment by dans77777** [comment]
![Screenshot (144)](https://user-images.githubusercontent.com/61909995/183044597-c9f9c7ce-e1c9-4d8e-a127-a42c7a5e526d.png)

@c-rindi  This is the screenshot of contribute.md file. here under contributing guide point I wanted to add one line description for developers about gh-pages branch and link to the same and also link for understanding the workflow of the project. bcz I know when I was new to this project during MLH journey , there was no way for me to know about gh-pages branch to work with website . also I wanted to change some sentence structure like they have given "send us a pull request" , raising a pull request is most appropriate according to the standard. these minor things surely makes high quality docs and really useful .

I hope this is clear to you.
Thank you

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1302?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by kindyluv** [comment]
Hi @dans77777 Please have you worked on this? and if no I want to work on it what do I need to know.

**Comment by kindyluv** [comment]
Hi @dans77777 Please have you worked on this? and if no I want to work on it what do I need to know.

**Comment by dans77777** [comment]
@kindyluv heyy, I already have a PR on this. can you please start with #1144 ? Thank you.
