### ISSUE TITLE
Make repository link clickable in the quickstart

### ISSUE THREAD

**Issue by dans77777** [G-Research/armada#1315]
repository link is not clickable , I will be adding clickable content.

**Comment by c-rindi** [comment]
Hi @dans77777 - can you add a little bit more detail to this PR, please? 
Which link are you referring to the in the QS?
Thank you.

**Comment by dans77777** [comment]
@c-rindi 
![Screenshot (139)](https://user-images.githubusercontent.com/61909995/183039380-63f87f75-dc24-48f8-9a3b-01608fcdfc28.png)


This is the screenshot of quickstart document, where they've given command to clone the repository where developers can copy and paste those commands and clone it. but what if they want to explore this repo on github? they probably need to search on google for armada repo or they needs to copy and paste URL manually or needs to see another documents. But as I worked with devrel , I think we should make "this repository" these words clikable , which will redirect users to the armada repository and they can click and explore repo if they want to do so. you can find "this repository" words in the sentence extact upper side of clonning command. these are very small issues and things which makes developers journey so so smooth.

I hope it's clear to all.
