### ISSUE TITLE
Update Python/Client README.md to explain our release process for python client

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1316]
With #1072 we are now able to manually run a release github action.  

https://github.com/G-Research/armada/blob/master/client/python/README.md#releasing should be updated to reflect our new release process.  

1) Create a PR that updates the pyproject.toml version number for the python client.
2) Merge that PR into main.
3) Select the Release PyPI action and deploy a new wheel file to PYPI.

**Comment by kannon92** [comment]
<img width="1282" alt="Screen Shot 2022-08-04 at 9 37 18 AM" src="https://user-images.githubusercontent.com/3780425/182861609-41587336-2747-4a7c-aa32-73c7515f6e2e.png">

This is how you select the release action for deployment.

**Comment by jayofdoom** [comment]
Going to knock this out + make a general pass over client/python/README.md for accuracy/layout
