### ISSUE TITLE
Add Events page to armadaproject.io

### ISSUE THREAD

**Issue by jayofdoom** [G-Research/armada#1317]
We want to add a Events (News+Events?) page to armadaproject.io. 

This page should include two primary kinds of news and events
- big events where Armada is featured or presented on should be presented on the page similar to what https://siembol.io/news looks like
- non-Armada focused events, presentations, or meetups where armada devs will be present -- this will be presented as an opportunity to network with armada contributors

**Comment by stackedsax** [comment]
I think this sounds great.  With the second bullet point, we can list things that aren't even k8s or hpc related, right?  Like when C and Tabatha head to BlackHat/DefCon/Diana Initiative, it's still a possible opportunity for people to meet in person and also might help fill out the page a bit.

**Comment by jayofdoom** [comment]
My idea was that we tie it to a google calendar/ICS, and literally have any event where an armada dev/contributor/anyone is attending and willing to have a stranger go "Hi, talk to me about Armada?" on the calendar. This would include things like the OpenStack PTG, which, while not dedicated for Armada, would be a good chance to catch me on the hallway track to talk Armada.

**Comment by stackedsax** [comment]
Yeah, exactly.  Perfect.  This might be a really easy opportunity for a DevRel MLH fellow to help add entries to the calendar and keep it up to date on behalf of the DevRel team.  I mean, any dev can add to it and we'll encourage people to update it themselves, but in case people forget it feels like an easy piece of bookkeeping that we can ask the fellows to do.  Thoughts, @c-rindi?

**Comment by c-rindi** [comment]
These seem like some good ideas. I'd probably want to assign calendar maintenance to someone on staff (am currently recruiting for a DevRel Social role) rather than an intern who will graduate the program in 3 months. 
Looping in @dans77777, who has been working on the Armada website too, and @tabathad who had similar ideas for Siembol and other conversations during Hacker Summer Camp next week.

**Comment by tabathad** [comment]
Great idea Jay! If I understand correctly, this would be a read-only, public calendar. It would display the events with a rep from any of the teams and projects present that is willing to meet with people while attending. I'm not clear if the intent is to have it available to book time with a GR person, using calendly or the like, or to build awareness that there will be a GR presence at XYZ event.

**Comment by jayofdoom** [comment]
So, lets keep the scope limited to the following:
Armada (and, eventually I guess each GR-OSS project) will get a calendar that will list times when Armada devs are going to be at public events able to chat.

If we want to enhance it from there; great -- but right now I'd like to keep this issue focused on going from 0 event pages for Armada to 1 :D

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1317?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott
