### ISSUE TITLE
protobuf processing redundancy and slowness in Dockerfile, makefile

### ISSUE THREAD

**Issue by richscott** [G-Research/armada#1319]
The recent changes to implement GRPC bindings for C#/.Net introduced redundancies in the build/proto/Dockerfile and makefile - the logic to copy proto files in the former should be removed, and all Make targets that do protobuf processing should use the `setup-proto` prerequisite target instead.

Also, the `setup-proto` Make target sequentially invokes many golang containers, each running a single `cp` command - these copy commands should be coalesced into a single container execution, to reduce Docker container spin-up time cost.

**Comment by kannon92** [comment]
Didn't auto close this.  Can close with #1320
