### ISSUE TITLE
`pod_spec` is optional in `create_job_request_item`

### ISSUE THREAD

**Issue by Sharpz7** [G-Research/armada#1322]
Since `create_job_request_item` can be passed either a single pod_spec, or multiple, we probably want to ensure both are considered optional, as we do not want users passing through both.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1322?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott
