### ISSUE TITLE
formatting fixes to the Quickstart

### ISSUE THREAD

**Issue by dans77777** [G-Research/armada#1326]
@c-rindi I have found out some formatting fixes for Armada Quickstart.  under One-click Setup script commands should be like a code and not a normal text. adding screenshot of it.
![Screenshot (147)](https://user-images.githubusercontent.com/61909995/183086210-2ba7a80d-3057-47c9-8610-8dc326ae1636.png)

**Comment by c-rindi** [comment]
Thank you for the additional details and the screenshot, @dans77777. That's useful.
It sounds like you want to make the URL's live (clickable), correct?

**Comment by dans77777** [comment]
@c-rindi  yes I want to make the URL's live (clickable) and also in proper format . currently that text and URL is on the same line and not able to recognize quickly what the text is and where the URL is. URL should be on next line with clickable function.
Thank you!
