### ISSUE TITLE
Make CancelJobSet event set cancelling user

### ISSUE THREAD

**Issue by JamesMurkin** [G-Research/armada#1328]
Currently CancelJobSet event messages do not contain the user id of the user who perform the cancellation.

That means cancellation events populate the user id with the queue name.

It is useful to know who cancelled things, for auditing purposes.

This line https://github.com/G-Research/armada/blob/b14170a59b43996d26167141d6dee774f67b0c47/internal/armada/server/submit_from_log.go#L509 shows where we set the user id as the queue name. As a starting point to where this issue needs to be fixed

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1328?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott
