### ISSUE TITLE
Update Python client with new CancelJobSet RPC call

### ISSUE THREAD

**Issue by JamesMurkin** [G-Research/armada#1329]
A new RPC endpoint was added to Armada `CancelJobSet` in https://github.com/G-Research/armada/pull/1312

We should update the python client to include (and possibly use) this new endpoint

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1329?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by kannon92** [comment]
@Sharpz7 has asked to pull this ticket in.
