### ISSUE TITLE
Report available resources separately for each priority class

### ISSUE THREAD

**Issue by dejanzele** [G-Research/armada#1340]

**Comment by dejanzele** [comment]
Currently, the executor (i.e., the in-cluster component of Armada) only reports free resources to the Armada server (the central component of Armada responsible for assigning jobs to executors). Available resources are reported on a per-node basis. To support preemption, the executor must report separately free resources and resources allocated to preemptible jobs.
More specifically, the executor must report total resources available and for each priority class the resources assigned to jobs of that priority class.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1340?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by dave-gantenbein** [comment]
Closing as duplicate
