### ISSUE TITLE
Assign jobs to full clusters containing preemptible jobs

### ISSUE THREAD

**Issue by dejanzele** [G-Research/armada#1341]

**Comment by dejanzele** [comment]
Currently, the Armada server only assigns jobs to an executor if the worker cluster managed by that executor has resources not assigned to any pod. To support preemption, the server should also assign jobs to executors if those jobs could be scheduled by preempting jobs currently running in that cluster.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1341?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by dave-gantenbein** [comment]
Closing as duplicate
