### ISSUE TITLE
SPIKE: investigate tooling for reproducing K8S errors

### ISSUE THREAD

**Issue by dave-gantenbein** [G-Research/armada#1344]

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1344?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by kannon92** [comment]
Chaos-Mesh seems to be a very useful tool for reproducing failures of pods,network, cpu etc.  I was not able to replicate a node failure.  

@carlocamurri and I think it may be useful to find faults/defects in an Armada setup to see if we don't lose events.  

However, the GR-OSS team doesn't really have a stable environment for testing this that replicates GR.
