### ISSUE TITLE
Update proto messages to support preemption

### ISSUE THREAD

**Issue by dejanzele** [G-Research/armada#1356]
Currently, the executor (i.e., the in-cluster component of Armada) only reports free resources to the Armada server (the central component of Armada responsible for assigning jobs to executors). Available resources are reported on a per-node basis. To support preemption, the executor must report separately free resources and resources allocated to preemptible jobs.

More specifically, the executor must report total resources available and for each priority class the resources assigned to jobs of that priority class. 

Implement by adding new fields to the proto message sent from the executor to the server with info on allocated resources. In particular, send a map from priority class to a report of the resources allocated to jobs with that priority class and a map of the total resources available.

**Comment by severinson** [comment]
I've made a prototype PR for this:

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1356?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott
