### ISSUE TITLE
Update executor to populate fields added in 1356

### ISSUE THREAD

**Issue by dejanzele** [G-Research/armada#1357]
Once we have added proto messages fields necessary to support preemption in 
https://github.com/G-Research/armada/issues/1356
we need to update the executor to update these fields.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1357?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott
