### ISSUE TITLE
Update the server to use proto message fields added in 1356

### ISSUE THREAD

**Issue by dejanzele** [G-Research/armada#1358]

**Comment by dejanzele** [comment]
just combine the resources allocated to all priority classes on the Armada server side.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1358?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott
