### ISSUE TITLE
Add specific error message for preempted jobs

### ISSUE THREAD

**Issue by dejanzele** [G-Research/armada#1359]
We need to notify users if their job was killed due to preemption. To that end, we should add a specific failure message for preemption. Similar to how OOM errors are handled.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1359?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott
