### ISSUE TITLE
Update lookout to show job preemptions.

### ISSUE THREAD

**Issue by dejanzele** [G-Research/armada#1360]
Similar to how we show failed jobs, we should have a label for preempted jobs.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1360?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by samclark** [comment]
I think it would be nice if the implementation of this ticket exposed the termination reason and covered the other reasons too (e.g. OOM).

**Comment by suprjinx** [comment]
so the preempted job remains "Failed" but add a termination reason ("Preempted").

**Comment by suprjinx** [comment]
Verified via manual test preemption shows job as failed in job table, and preempted timestamp is populated

![Screenshot 2022-11-08 155017.jpg](https://images.zenhubusercontent.com/630fb03d1bd2366fee160252/8f684992-949a-4dc9-92ee-ac82e0345ba8)
