### ISSUE TITLE
Golang-ci should be able to run without errors.

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1365]
We added a new linter to our CI pipeline for go code.  We are only failing if any new changes break the linter.  

It would be ideal if we can fix any existing linter issues.  

We are using golang-ci and you can run the linter via golang-ci run.  

From dejan:

> I think we should start with running gofumpt on the whole codebase, gofumpt is the de facto standard for Golang coding style
Also, golangci-lint supports the --fix flag, which fixes non-dangerous lints, which can fix a lot of common and safe stuff out-of-the-box for us

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1365?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by dave-gantenbein** [comment]
Resolved by PR 1418
