### ISSUE TITLE
JobService panics if directory for SQLite db does not already exist

### ISSUE THREAD

**Issue by richscott** [G-Research/armada#1388]
If the directory for the SQLite database that JobService uses (as specified for the key `databasePath` in `config/jobservice/config.yaml`) does not already exist, JobService will immediately panic and exit.  The panic is preceded by a misleading error that SQLite is "out of memory". 

The code should check for the existence of the directory, and if not there, it should attempt to create it. If the creation fails, it should log and exit.

**Comment by kannon92** [comment]
Merged with #1389
