### ISSUE TITLE
Guide for deploying Armada on EKS

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1392]
Dejan has started some work on some teraform scripts for deploying Armada into production.  

We met with some people at the Innovation Lab who are interested in deploying Armada On-Prem and in the cloud.  I showed them Dejan's repo https://github.com/dejanzele/armada-infra and they were very interested in this.  We should make this part of our repo.

We should make this accessible as a guide so people can run a production cluster in the public cloud.  

1) Readme/Guidelines for setting up EKS
2) Teraform scripts
3) Example Values for Armada charts.
4) Simple script to deploy

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1392?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by dave-gantenbein** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1392?planning-poker) with Zenhub @suprjinx

**Comment by kannon92** [comment]
Reopening because we should migrate the repo to our current repo.  Leaving this open so we keep this tracked.
