### ISSUE TITLE
Lookout: JobSets view has no Cancelled column, JobSets disappear if all jobs are cancelled.

### ISSUE THREAD

**Issue by robertdavidsmith** [G-Research/armada#1398]
Hi,

In Lookout, if you submit a JobSet, then cancel all its jobs, the jobset disappears from the JobSets view. This is the case even with "Active Only" unticked.

This is possibly related to there being no cancelled column in the JobSets view.

Please can someone
1) Add a Cancelled column to the JobSets view
2) Ensure that JobSets with all jobs Cancelled don't disappear from the JobSets view.

Thanks,

Rob

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1398?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by kannon92** [comment]
@kindyluv is working on this issue.

**Comment by dave-gantenbein** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1398?planning-poker) with Zenhub @suprjinx
