### ISSUE TITLE
Create REST API definitions for Lookout API 

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1401]
Discussions with GR have made it clear that we want to no longer support REST API in Armada.  With GRPC clients for python and C#, we are able to migrate clients to use GRPC.

However, lookout still uses REST API for both the Armada endpoints and their own endpoints.  

We should convert lookout.proto into a rest api definition.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1401?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by dave-gantenbein** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1401?planning-poker) with Zenhub @suprjinx
