### ISSUE TITLE
Jupyter-Armada Integration for Interactive jobs

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1402]
We should have OSS tutorials about using armada and jupyter notebooks.  Carlo mentioned that they enabled Ingress and such for MLE so MLE is able to run jupyter notebooks and hook up to armada.  Of course this is totally undocumented and hidden under GR. 

Note this is different from user a jupyter notebook to submit a job but more of an interactive job.  In HPC space, this is technically denoted as an interactive job where you request a node and you then are able to log into that node and run an interactive job.  

We should write a tutorial that allows setup of this as this is a pretty useful case for ML.

The Machine Learning Engineer team at GR has a project where they created a library that uses the python-rest client to submit a jupyter job.  I suggest we go with a special client library that uses the armada-grpc library to launch a jupyter job and have a user be able to use that link in the pod.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1402?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by kannon92** [comment]
This is really a large feature request.  We have created a repo (https://github.com/G-Research/armada-jupyter) and future work will be found there!
