### ISSUE TITLE
Add examples for new gRPC calls

### ISSUE THREAD

**Issue by Sharpz7** [G-Research/armada#1420]
Examples need to be added for the features added in:
- https://github.com/G-Research/armada/pull/1419
- https://github.com/G-Research/armada/pull/1413

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1420?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott
