### ISSUE TITLE
Construct EC2 instance for dev/testing of Jupyter notebook with K8S

### ISSUE THREAD

**Issue by richscott** [G-Research/armada#1424]
Construct an EC2 instance (same sizing as recommended in current Armada docs for dev/testing) to be used for development and testing of Jupyter notebooks with K8S.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1424?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott
