### ISSUE TITLE
Set z-index to the buttons in the armada website 

### ISSUE THREAD

**Issue by AnkitaMalik22** [G-Research/armada#1442]
The top & bottom buttons should have greater stack order or shown on top

![Screenshot_20220901-104804.png](https://user-images.githubusercontent.com/80139836/187841221-47cd4acb-34dd-47af-9a13-8d65d3a2b261.png)

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1442?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by dave-gantenbein** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1442?planning-poker) with Zenhub @suprjinx

**Comment by kannon92** [comment]
Hello @AnkitaMalik22, Thank you for the github issue!  Are you open to creating a PR to fix this?

**Comment by dans77777** [comment]
@kannon92 I am taking this issue ! as I have worked upon these buttons, I can do better improvements quickly. Thank you @AnkitaMalik22 for the github issue!
