### ISSUE TITLE
Golangci should report the line error and warning in the CI.

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1444]
Currently, we run the golangci in our github action workflow.  It will fail if it detects an error but it will not show the line number or warning.  

This is not ideal.  We should enable golangci to report errors in the CI log.

**Comment by kannon92** [comment]
https://github.com/golangci/golangci-lint-action/issues/362 is a relevant issue for this ticket.

There seems to be three options: run the linter twice, run multiple times or run without the github action.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1444?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by dave-gantenbein** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1444?planning-poker) with Zenhub @suprjinx

**Comment by shafink11** [comment]
Hey this is my first comment on here. We could add this under step: in the action.yml file in the go-setup
- name: Display lint results
      run: golangci-lint run
      if: always()
      shell: bash

Of course this would be going with the first option of running the linter twice which is not optimal but it does make it more simple to understand the errors.

**Comment by kannon92** [comment]
Hey @shafink11 This sounds like a potential option.  

Feel free to open up a PR with this change if you are up for it.

**Comment by shafink11** [comment]
Okay I created a PR
Thank you for the response

**Comment by kannon92** [comment]
https://github.com/G-Research/armada/pull/1614 solves this.
