### ISSUE TITLE
Advertise CNCF sandbox status in armadaproject.io & project documentation

### ISSUE THREAD

**Issue by jayofdoom** [G-Research/armada#1446]
Now that we are a CNCF sandbox project, we should indicate it on our web presence and readmes.

We should, at a minimum:
- Add a CNCF badge / sandbox badge to our above-the-fold main page or a blurb about being sandbox if a badge doesn't exist
- Ensure top-level project readmes indicate we are CNCF sandbox
- If the news page exists by the time this issue is address, ensure a news item exists about our selection to the CNCF sandbox

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1446?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by dave-gantenbein** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1446?planning-poker) with Zenhub @suprjinx
