### ISSUE TITLE
Make E2E Tests Easier To Debug

### ISSUE THREAD

**Issue by d80tb7** [G-Research/armada#1459]
Right now the E2E tests are quite hard to troubleshoot if something goes wrong.  The main issue I face is that there is no way of replacing one of the components (e.g. the server) with one that you have attached a debugger to.  As a result I often find myself trying to debug via `println` which is somewhat slow going.  I think in an ideal world debugging these tests would work as follows:

1. Run some command (ideally a docker compose) to bring up the system into a state suitable for the e2e tests.  This command should allow you to specify which Armada components you *don't* want to bring up.
2. Launch the Armada component(s)  that you excluded in 1) from your IDE. This enables them to be debugged if necessary
3. Run the E2E Tests (ideally from your IDE).  Any Breakpoints specified in 2) will be hit.
4. Quickly reset the system to the initial state.

Things to think about:
- Right now we create a special network for everything to run on (I believe we do this because otherwise KIND doesn't work on WSL), but this means that it's hard to have a non-docker component (i.e. something running in your ide under a debugger) talking to the other armada components/
- There is some functionality in the armada makefile to do some of this already (e.g. run without setup), maybe some of this could be reused.
- Our makefile is already pretty complex, any solution that can reduce complexity (e.g. by using docker compose) would be good
- The above mechanism should also allow for developing against the whole armada system locally if required.
- Whatever solution we come up with should also be used for the actual E2E tests.

**Comment by severinson** [comment]
We have at least these methods for bringing up an environment:
https://github.com/G-Research/armada/tree/master/docs/dev
https://github.com/G-Research/armada/blob/master/makefile#L388

And some setup scripts here:
https://github.com/G-Research/armada/tree/master/scripts

I think the above should be merged into a single procedure.

The default config for e2e tests are here:
https://github.com/G-Research/armada/tree/master/e2e

The default config for built components are here:
https://github.com/G-Research/armada/tree/master/config

I think we should merge these to have a single default config that we also use for e2e tests. At least as far as possible.

We have both the legacy e2e tests and the new test suite now. I'd like to replace the legacy e2e tests with the test suite.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1459?planning-poker) with Zenhub @suprjinx @dejanzele @richscott @kannon92 @jayofdoom
