### ISSUE TITLE
Create Test Tools To Allow Developing Individual Armada Components In Isolation

### ISSUE THREAD

**Issue by d80tb7** [G-Research/armada#1460]
Traditionally all Armada development has been done by running the entire armada system.  As Armada becomes larger and more complex, this becomes increasingly difficult to do.  instead, as each subcomponent has a well defined role and a clear interface it should be possible to develop them in isolation.   

As an example consider Lookout development.  This could be done either by just having a tool to populate the database (in which the only components needed is sql server) or alternatively by also running lookout-ingester and pulsar and just having a tool to publish messages onto pulsar.

Each component probably needs analysis to see what it would need, but I think we could get a long with with:
a) having some easy way of starting up a subset of components
b) having an easy tool to publish messages onto pulsar
c) having an easy tool to view messages on pulsar
d) having an easy tool to directly put data into the lookout db.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1460?planning-poker) with Zenhub @suprjinx @dejanzele @richscott @kannon92 @jayofdoom

**Comment by dave-gantenbein** [comment]
Convert this epic.

**Comment by richscott** [comment]
This ticket has been converted to an epic - see the epic "Test Tools for Component Development" at

https://app.zenhub.com/workspaces/armada-62c744dc3b819100132ca032/epics?activeEpic=Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTA2MDcz&state=OPEN&state=TODO&state=IN_PROGRESS
