### ISSUE TITLE
Lookout: display job termination reason in job details view

### ISSUE THREAD

**Issue by samclark** [G-Research/armada#1478]
Users would like to see the job termination reason in the job details view (e.g. oom, preempted, ...).

Related to: https://github.com/G-Research/armada/issues/1360

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1478?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott @suprjinx

**Comment by suprjinx** [comment]
I think the Error field will show the underlying reason for termination

**Comment by kannon92** [comment]
@samclark I believe @suprjinx is correct.  You can clearly see why the job failed and it says it was killed to OOM.  

Should we close this ticket?

<img width="916" alt="Screen Shot 2022-10-06 at 10 29 08 AM" src="https://user-images.githubusercontent.com/3780425/194340174-e57cb80b-66f6-4043-9c5a-f684e61a75f3.png">
