### ISSUE TITLE
Lookout: horizontal scrolling

### ISSUE THREAD

**Issue by samclark** [G-Research/armada#1481]
Currently the width of the tables in lookout are determined by the width of the browser window. Users would much prefer to have columns be sensible widths (not determined by browser width) and have the columns extend past the edge of the browser window (and viewed by scrolling horizontally).

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1481?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott @suprjinx

**Comment by kannon92** [comment]
Reading about react-virtualized a bit more.  It sounds like horizontal scrolling is not recommended.  

https://stackoverflow.com/questions/46177344/react-virtualized-table-x-scrolling

The last answer to that thread mentions that if we add horizontal scrolling, we lose the virtualized feature of the table.  

Should we investigate a new table component for Jobs if this is a really strong feature request?  

React-Virtualized also seems to not be in active development.
