### ISSUE TITLE
Lookout: time in state column

### ISSUE THREAD

**Issue by samclark** [G-Research/armada#1482]
Users would like a new job view column which displays how long the job had been in its current state (queued, running, succeeded, failed, etc...).

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1482?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott @suprjinx

**Comment by suprjinx** [comment]
Added this column with string like "2m" or "2d"
![armada-time-in-state.jpg](https://images.zenhubusercontent.com/630fb03d1bd2366fee160252/29cb9f22-ffe8-4f9a-ab4e-53697a3f2f15)
