### ISSUE TITLE
Lookout: command line columns

### ISSUE THREAD

**Issue by samclark** [G-Research/armada#1483]
Users would like two new job view columns:
1) one which displays the command line of the pods
2) one which displays the command line arguments of the pods

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1483?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott @suprjinx

**Comment by kannon92** [comment]
Considering that command and arguments can be arbitrary size and are actually multi container, I think we may need some more details on presenting this information.

Say a container has a 1000 character command (and this can also be a list of values) and 5-10 arguments, are we really aiming to present all this information in a column?  How do we want the separation of command arguments considering they are a list of strings in YAML?  



This information will also be put in the job details and we can probably implement better UX there than in a column.
