### ISSUE TITLE
Lookout: cluster name column

### ISSUE THREAD

**Issue by samclark** [G-Research/armada#1484]
Users would like a new job view column which displays the cluster the job is running on / ran on.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1484?planning-poker) with Zenhub @ClifHouck @dejanzele @richscott @Sharpz7 @suprjinx
