### ISSUE TITLE
Lookout: node name column

### ISSUE THREAD

**Issue by samclark** [G-Research/armada#1485]
Users would like a job view column which displayed the name of the Kubernetes node that the job is running on / ran on.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1485?planning-poker) with Zenhub @ClifHouck @dejanzele @richscott @Sharpz7 @suprjinx
