### ISSUE TITLE
Lookout: yarn package manager

### ISSUE THREAD

**Issue by samclark** [G-Research/armada#1486]
In an effort to speed up builds we should move to using yarn as the package manager.

**Comment by suprjinx** [comment]
I can't seem to get around this error -- yarn forces a breaking change in tsconfig.json:
``docker run --rm -v /Users/gwilson/Projects/armada-suprjinx:/go/src/armada -w /go/src/armada/internal/lookout/ui -e npm_config_disturl -e npm_config_registry node:16.14-buster yarn build
yarn run v1.22.18
$ react-scripts build
The following changes are being made to your tsconfig.json file:
  - compilerOptions.jsx must be react-jsx (to support the new JSX transform in React 17)

Creating an optimized production build...
Failed to compile.

/go/src/armada/internal/lookout/ui/src/components/job-sets/DurationPlotsTable.tsx
TypeScript error in /go/src/armada/internal/lookout/ui/src/components/job-sets/DurationPlotsTable.tsx(129,8):
'Table' cannot be used as a JSX component.
  Its instance type 'Table' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'import("/go/src/armada/internal/lookout/ui/node_modules/@types/react-virtualized/node_modules/@types/react/index").ReactNode' is not assignable to type 'import("/go/src/armada/internal/lookout/ui/node_modules/@types/react-transition-group/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.  TS2786

    127 |       }}
    128 |     >
  > 129 |       <Table
        |        ^
    130 |         height={props.height}
    131 |         width={props.width}
    132 |         rowCount={props.durations.length}


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [build-dev-lookout] Error 1

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1486?planning-poker) with Zenhub @ClifHouck @richscott @suprjinx @dejanzele @Sharpz7

**Comment by headphonejames** [comment]
worked for me.

docker run --rm -v /home/ubuntu/armada/:/go/src/armada -w /go/src/armada/internal/lookout/ui -e npm_config_disturl -e npm_config_registry node:16.14-buster yarn build
yarn run v1.22.18
$ react-scripts build
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Compiled successfully.

File sizes after gzip:

  215.03 KB  build/static/js/2.1b9acce0.chunk.js
  40.02 KB   build/static/js/main.4f568cd8.chunk.js
  2.23 KB    build/static/css/main.2dc6f2d5.chunk.css
  1.39 KB    build/static/js/3.92d6cc51.chunk.js
  1.17 KB    build/static/js/runtime-main.ab27fb8a.js
  403 B      build/static/css/2.b0c8ef5b.chunk.css

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  https://cra.link/deployment

Done in 45.89s.

**Comment by kannon92** [comment]
The PR is about switching to use yarn instead of npm in our build. If it works for you could you switch it as part of this PR?
