### ISSUE TITLE
[Lookout] Use orig_job_spec rather than job column for displaying the job yaml

### ISSUE THREAD

**Issue by d80tb7** [G-Research/armada#1494]
Lookout uses the `job.job` database column to display the job yaml.  This is a binary json column, which is unfortunately slow to ingest.

To solve this, lookout ingester has started populating the `job.orig_job_spec` column which is the same data contains gzip compressed proto data stored in a postres bytea column,

We are now populating both columns, and have been for some time, so we can move over to the new column and delete the old one.  To do this we need to:

a) change lookout to take the job yaml from the `orig_job_spec` column.
b) change lookout ingester to no longer populate the old `job` column
c) change the lookout schema to drop the old `job` column.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1494?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott @suprjinx
