### ISSUE TITLE
Make Lookout Part of E2E Tests

### ISSUE THREAD

**Issue by d80tb7** [G-Research/armada#1495]
Currently the E2E tests don't test any of lookout.  Testing the UI might be hard, but we should at least be able to test the state of the database fairly easily.  I think to do this we need to:

1. Make lookout-ingester be instantiated as part of e2e tests
2. Write a test that asserts the state of the database (job in right state, correct number of job runs, job yaml as expected etc)

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1495?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott @suprjinx

**Comment by ClifHouck** [comment]
Going to take a look at this.
