### ISSUE TITLE
Enable GRPC heartbeating Between the Server and Executor

### ISSUE THREAD

**Issue by d80tb7** [G-Research/armada#1496]
Now the Server supports grpc heartbeating we should enable this between the server and the executor.  This should enable the executor more quickly fail if the connection has been interrupted.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1496?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott @suprjinx

**Comment by d80tb7** [comment]
A bit more information:

- The executor communicates with the server via grpc calls.  There are a couple of calls it makes.  The first is to report usage and the second is to report events.
- We want to enable heartbeating on these calls, which is a property that's set when you create the grpc client.  
- It's possible that we don't need any code changes to do this.  I had a quick look and it looks like the executor creates the client in `application.createConnectionToApi`.  This passes through `config.ApiConnection` which has heartbeating properties already present.  In this case I think we need to a) show that `application.createConnectionToApi` is the *only* place the executor creates the connection and b) run a test to set these properties and see that they work as expected.

**Comment by dejanzele** [comment]
Example config for client-side keepalive.
```
config/executor/config.yaml

grpc:
  permitWithoutStream: true
  time: 10s
  timeout: 20s
```

**Comment by dejanzele** [comment]
To easily test & validate grpc pings are being sent, set the envvar `GODEBUG=http2debug=2` before running the executor, and then gRPC will log packages sent over the wire.
