### ISSUE TITLE
Add Prometheus Metrics for the Lookout Ingester

### ISSUE THREAD

**Issue by d80tb7** [G-Research/armada#1497]
Add some Prometheus metrics (suitable for alerting) for the lookout ingester.  Examples include:

* Failed to deserialize messages
* Lost connection to pulsar
* Error processing messages
* Failure to insert into db

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1497?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott @suprjinx
