### ISSUE TITLE
Improve the error message when you don't have perms

### ISSUE THREAD

**Issue by d80tb7** [G-Research/armada#1499]
When you make a call to the Armada Server GRPC interface and you don't have permissions, an error like the following is returned:
```
{"error":"Request in not authenticated with any of the supported schemes.","code":16,"message":"Request in not authenticated with any of the supported schemes."} 
```

We should improve this to give more info. For example, which schemes were tried and what action it tried to take.

**Comment by kannon92** [comment]
I believe there is already an issue for this.

https://github.com/G-Research/armada/issues/1370
