### ISSUE TITLE
Reformatting one click setup in Armada Quickstart

### ISSUE THREAD

**Issue by dans77777** [G-Research/armada#1501]

**Comment by dans77777** [comment]
![Screenshot (188)](https://user-images.githubusercontent.com/61909995/191017075-cb626c0a-b56e-4c26-83aa-2606a5aadbc6.png)


The links under "one-click setup" are working when we see on github but not on the https://armadaproject.io/quickstart.

**Comment by suprjinx** [comment]
One-click setup has been removed with the "quickstart" guide.
