### ISSUE TITLE
Fixing broken links in Armada API

### ISSUE THREAD

**Issue by dans77777** [G-Research/armada#1503]

**Comment by c-rindi** [comment]
Hi @dans77777 - can you please add some details about which links you're fixing? Thanks.

**Comment by dans77777** [comment]
![Screenshot (184)](https://user-images.githubusercontent.com/61909995/191009769-8ae548e8-9366-4bf2-9603-12be02c2017d.png)
fixing the link of grpc-gateway that you can see under heading REST.
