### ISSUE TITLE
Write Pulsar message-receiving client for testing

### ISSUE THREAD

**Issue by richscott** [G-Research/armada#1506]
Using the data defintions and logic in `internal/pulsarutils/pulsarclient.go` and `messageid.go`, write a basic Pulsar client program that (optionally, authenticates first) to a Pulsar cluster, and continuously polls (select's) from a channel as supplied by the `Receive()` func in internal/pulsar/async.go.  Connection configuration should be specifiable via command-line flags.

Interrupting the program (ctrl+c / SIGINT) should close the context and terminate the program.

This issue is part of the suite of tools specified in #1460.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1506?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott @suprjinx
