### ISSUE TITLE
Expose health check as gRPC endpoint in services

### ISSUE THREAD

**Issue by suprjinx** [G-Research/armada#1508]
`pkg/client/connection.go` includes an ArmadaHealthCheck() function -- but this appears to invoke the Armada /health endpoint via REST.

For this ticket, make health an endpoint we can invoke with the gRPC client, for both Submit and Event services.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1508?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott @suprjinx
