### ISSUE TITLE
SPIKE: engage with community on https://github.com/kubernetes-sigs/kueue/issues/83

### ISSUE THREAD

**Issue by dave-gantenbein** [G-Research/armada#1529]

**Comment by kannon92** [comment]
Before we engage with the wg-batch community, I recommend we write down what we actually did for preemption.

https://github.com/G-Research/armada/issues/1532

I hope @dejanzele, @severinson or @d80tb7 can help with this.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1529?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott @suprjinx

**Comment by kannon92** [comment]
Good news.  Someone mentioned that they are taking up a proposal for preemption in Kueue.  We can link when it is ready.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1529?planning-poker) with Zenhub @ClifHouck @dejanzele @richscott @Sharpz7 @suprjinx

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1529?planning-poker) with Zenhub @ClifHouck @dejanzele @headphonejames @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by kannon92** [comment]
There is a large amount of community engagement on this issue.
