### ISSUE TITLE
Spike: Pod Failure Policy (K8 1.25 alpha feature) Can we utilize this in Armada?

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1537]
In 1.25, the wg-batch/sig-scheduling has added an ability to retry Pods/Jobs based on error codes.  

https://github.com/kubernetes/enhancements/issues/3329

Docs: https://kubernetes.io/docs/tasks/job/pod-failure-policy/

We should investigate if we can use this to clean up our logic for executor pod retries.  

Currently, we have code in our executor that does this in a non standard way.  https://github.com/G-Research/armada/blob/master/internal/executor/configuration/podchecks/types.go

We should investigate if we can map some of this functionality to use Pod Failures.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1537?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott @suprjinx

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1537?planning-poker) with Zenhub @ClifHouck @dejanzele @richscott @Sharpz7 @suprjinx

**Comment by kannon92** [comment]
I don't think this KEP will be useful to Armada as is.  

In the KEP, their non goal is to support pending phase of pods.  This means they are not targeting image pull issues or any pending issue that could cause the pod to not be scheduled.  

I created an issue in the Kubernetes repo to start this conversation.  

https://github.com/kubernetes/kubernetes/issues/113211

The only outstanding question is if GR would be interesting in retrying based on exit codes for the containers?  

@JamesMurkin any thoughts on this last point?

**Comment by kannon92** [comment]
@JamesMurkin mentions that the interest in retrying is usually based on Pending.  There hasn't been much request on exit code retrying.
