### ISSUE TITLE
CNCF Slack link is not working

### ISSUE THREAD

**Issue by dans77777** [G-Research/armada#1583]
We have contributing guide https://armadaproject.io/contribute where CNCF slack 1st point link is not working. needs fix
![Screenshot (204)](https://user-images.githubusercontent.com/61909995/193551508-07395995-9895-4364-a324-1af23bbf8fc2.png)

**Comment by dans77777** [comment]
@jayofdoom can you please share the correct link here , so I can fix it.

**Comment by kannon92** [comment]
Hello @dans77777, the correct link is https://slack.cncf.io/.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1583?planning-poker) with Zenhub @ClifHouck @dejanzele @headphonejames @kannon92 @richscott @Sharpz7 @suprjinx
