### ISSUE TITLE
Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork

### ISSUE THREAD

**Issue by dave-gantenbein** [G-Research/armada#1602]

**Comment by kannon92** [comment]
Can you add more details to this?  Can we just use our logo as artwork?

**Comment by dave-gantenbein** [comment]
Yes.

**Comment by kannon92** [comment]
Looks like we got to create a few more logos before we upload to CNCF:

> We prepare artwork in 2 formats (PNG & SVG), 3 layouts -- horizontal (also known as landscape format), stacked (which is closer to square), and icon (which does not include the name and is square), and at least 3 versions (color/black/white). So, that's at least 18 versions of most logos.

I think we have the stacked one in 3 different colors but we don't have horizontal or icon.  

So this ticket should include creating these logos and then uploading them to CNCF.

**Comment by stackedsax** [comment]
I think this logo was done via Two Hats Consulting.  I'm sure they can churn it out pretty quickly, but @c-rindi or I may need to jump up and down to get their attention.  If you want to get this one across the line before KubeCon, we should start that process today.

**Comment by kannon92** [comment]
@dave-gantenbein has suggested that this would be useful to have before KubeCon.  

@stackedsax and @c-rindi could we see about getting this by then?

**Comment by c-rindi** [comment]
I've reached out to Two Hats and will update when I hear back.

**Comment by dave-gantenbein** [comment]
[https://app.zenhub.com/files/192768713/f9ecfa8e-8562-4b79-bb8a-8789033171db/download](https://app.zenhub.com/files/192768713/f9ecfa8e-8562-4b79-bb8a-8789033171db/download)

**Comment by kannon92** [comment]
TY everyone.  I will get this opened up on cncf tomorrow!

**Comment by kannon92** [comment]
https://github.com/cncf/artwork/pull/364
