### ISSUE TITLE
ArmadaOperator: Lookout url feature request

### ISSUE THREAD

**Issue by iJanki-gr** [G-Research/armada#1603]
Hello,

I have a feature request for armada operator in Airflow.
It would be desirable if in the task log a link to the Armada Lookout UI job view is printed.

ArmadaOperator could accept an addition parameter and/or read it from an ENV variable that would look like:

lookout_url_template: "https://lookout.armada.xxx/jobs?job_id=<JOB_ID>&newest_first=true"

That would allow the user to quickly check job status in armada and also to see the logs from the Lookout interface.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1603?planning-poker) with Zenhub @ClifHouck @dejanzele @headphonejames @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by ClifHouck** [comment]
Going to take a look at this.
