### ISSUE TITLE
armadaproject.io: remove references to the term "quickstart", replace with "Demo" -> link to AWS demo site

### ISSUE THREAD

**Issue by dave-gantenbein** [G-Research/armada#1605]

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1605?planning-poker) with Zenhub @suprjinx @richscott @Sharpz7 @dejanzele @ClifHouck @headphonejames @kannon92

**Comment by kannon92** [comment]
There are some security implications with exposing a public URL that anyone can submit jobs too.  How do we want to throttle users if they abuse this too much?  I guess we can have a minimal AWS cluster that won't incur too much cost if someone tries to submit a lot of jobs?

**Comment by dave-gantenbein** [comment]
Let's make it minimal as a first step. We can add throttling as a follow up story. Good catch.

**Comment by Sharpz7** [comment]
To the best of my knowledge, this is being blocked by the fact that its not active right now: https://ui.dev.armadaproject.io/

Unless the link has changed @dejanzele ?

**Comment by suprjinx** [comment]
this is the uri: https://ui.demo.armadaproject.io/

**Comment by Sharpz7** [comment]
Maybe a solution here is people can request demo credentials from our website, and they only work for 24hrs?

**Comment by suprjinx** [comment]
i'm not really clear what we're doing with this story @dave-gantenbein  -- "Quickstart" seems to concern running locally, so it seems like we'd update to use localdev docker-compose and all it "Developement". The Demo site is kind of a new concept for these docs -- a production install already running to "try it out".

**Comment by dave-gantenbein** [comment]
"Quickstart" as a term seems to cause confusion, as seen here! The term should be deprecated, and we either link to the demo site in AWS or the developers guide. Make sense?
