### ISSUE TITLE
ArmadaOperator: Add airflow task id to Armada annotations

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1608]
When a user submits an Airflow task, we should add the airflow task id to the Armada annotations.

An example can be below: 
```
jobSetId: test
priority: 100
namespace: batch-test
annotations:
  armadaproject.io/taskRunId: 0a016adf-8325-1d6a-8183-268de7a625ea 
  ````

**Comment by kannon92** [comment]
@iJanki-gr Is there any other items in the airflow context that you would want added as annotations?  

I believe everything is in place to add the annotations, we just need to read them from airflow context and create them in the job request.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1608?planning-poker) with Zenhub @ClifHouck @dejanzele @headphonejames @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by suprjinx** [comment]
@kannon92 it seems like airflow has a "task_id" and a "run_id" as separate identifiers -- which should be used for "taskRunId" in the description?

**Comment by kannon92** [comment]
Please hold on this. I need to meet with Danielle to discuss airflow user request but it will have to happen after Kubecon.

**Comment by kannon92** [comment]
So @iJanki-gr and I meant to sync up before I left for Kubecon.  He has some ideas of what potential airflow users would want from this work but I think we need to see some DAGs and see what is possible.  

At this moment, we use dagrunId as our job-set name.  There was a request to dynamically use task name from armada job ids but I don't know if that is possible.  Airflow seems to want static task names but it seems possible to do dynamic generation of dags but it seems to be an advanced feature so I think more information is necessary.  Feel free to take lead on this if you want with Daniele.
