### ISSUE TITLE
Lookout: Investigate use of different React tables

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1629]
React-Virtualized seems to be no longer actively developed and doesn't have a lot of features that users would want (horizontal scrolling).  The last release of react-virtualized was in 2020.  

https://ui-lib.com/blog/reactjs-table-libraries/

https://www.ag-grid.com/react-data-grid/ also has an extensive demo that fits all the features that we want.  

The other option is to no longer us the Table of react-virtualized and use Grid.  I believe Grid can allow virtualization and horizontal scrolling.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1629?planning-poker) with Zenhub @ClifHouck @dejanzele @headphonejames @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by kannon92** [comment]
@carlocamurri has started using react data table in v2.  He suggests we close this one.
