### ISSUE TITLE
Create teardown script for localdev

### ISSUE THREAD

**Issue by Sharpz7** [G-Research/armada#1647]
Create a script to remove the cluster, containers and anything else used by the localdev run script.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1647?planning-poker) with Zenhub @ClifHouck @dejanzele @headphonejames @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by ClifHouck** [comment]
Since I need to learn about the *new* dev environment I'll take this on.
