### ISSUE TITLE
Lookout: Overview Page View should have more states represented.

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1657]
The Overview page has Queued, Pending and Running.

<img width="1133" alt="Screen Shot 2022-10-18 at 9 08 13 AM" src="https://user-images.githubusercontent.com/3780425/196438650-4b4199f4-0807-4cc8-b6f0-5a2a89dff724.png">

We should add Failed, Succeeded and Cancelled(optional) to this page.  It looks very odd to have all your queues disappear once they are finished running.   

This will require a lookout API change in addition to UI components.

**Comment by dave-gantenbein** [comment]
I wonder if this is something Ogi weighed in on - @carlocamurri did you guys discuss this table?
