### ISSUE TITLE
Cleanup: Remove dev-armada from docs/dev

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1663]
With @suprjinx work on localdev, we no longer need the dev-armada make target and the config files.  

A correspond PR should address the following:

1) Remove docs/dev/config
2) Remove references to dev-armada make target and its correspond items.
3) Update docs/dev/README.md to point to new method for setting up development environment.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1663?planning-poker) with Zenhub @ClifHouck @dejanzele @headphonejames @kannon92 @richscott @Sharpz7 @suprjinx
