### ISSUE TITLE
E2E Test for Preemption 

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1664]
@severinson has enabled preemption in his new scheduler.  

We should create a e2e test that replicates preemption.  This should include our user guide examples so we can keep these up to date as part of the CI.  

1) Create a e2e test following e2e structure.
2) Follow directions in user guide to create a environment where preemption can occur

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1664?planning-poker) with Zenhub @ClifHouck @dejanzele @headphonejames @kannon92 @richscott @Sharpz7 @suprjinx
