### ISSUE TITLE
Check Performance Of New Scheduler When Recovering State From Postgres

### ISSUE THREAD

**Issue by d80tb7** [G-Research/armada#1677]
The new scheduler has the concept of a "scheduling key" which is all the information needed to schedule a job (resources, tolerations, nodeaffinities etc). The plan is to store this in Postgres with one row per job.

On startup, the scheduler needs to query for all scheduling keys before it can start scheduling.  This means that if we have a very large number of queued jobs (lets say 20 million) we are going to be fetching a very large number of rows from postgres. This situation becomes worse if we consider that we will be multiple scheduelr instances (for redundancy) and thus the load on postgres will increase further if more than one restarts at the same time.

We therefore need to investigate how the system performs in this case.  I would suggest some sort of (rough) benmark of the following:
Start a postgres server an put 20 million scheduling keys in it
Time how long it takes if a single reader tries to extract all keys
Time how long it takes if 3 concurrent readers are trying to extract all keys

NOTE: the following will require new tickets and design work
If this proves that postgres will not like this- we need to come up with alternatives.  A couple of ideas I had were:
1) Write the scheduling keys onto pulsar (will probably need to be a single-partition topic)  and read from there
2) Periodically have the scheduler dump its current state to file.  On restart it can bootstrap from the file and then read only the scheduling keys that have been updated from postgres.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1677?planning-poker) with Zenhub @ClifHouck @dejanzele @headphonejames @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by dave-gantenbein** [comment]
Note: we are sizing this as running the test. We will create additional tickets for the remedy if its found to be necessary.

**Comment by dejanzele** [comment]
this might be already done by @d80tb7

**Comment by ClifHouck** [comment]
Going to take a look at this, assuming it's not already done.

**Comment by d80tb7** [comment]
sorry yes I did this- TLDR it's fine.
