### ISSUE TITLE
Show queue names as you type in job queue search field

### ISSUE THREAD

**Issue by ClifHouck** [G-Research/armada#1679]
Comes out of discussion in #908 by @JamesMurkin 

It would be nice if a drop-down list of queues matching (or maybe close to) the current search string was displayed. Imagine the google search bar drop down.

Priority uncertain.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1679?planning-poker) with Zenhub @ClifHouck @dejanzele @headphonejames @kannon92 @richscott @Sharpz7 @suprjinx
