### ISSUE TITLE
Add E2E Tests for Airflow Operator [Without Airflow]

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1773]
We have https://github.com/G-Research/armada/blob/master/third_party/airflow/tests/integration/test_airflow_operator_logic.py which functions as a local integration test.  

We should add this into our github actions as part of our integration tests.  

The work needed:

1) Setup the e2e environment using localdev
2) Install all the python dependencies (armada-client, airflow-operator, etc)
3) Write a github action that runs pytest on the test_airflow_operator.

Monitor test to make sure it is not fickle.

**Comment by suprjinx** [comment]
airflow is now an optional localdev service, so i think we'd just need to start it and `exec` into the service to run the pytest command
