### ISSUE TITLE
Add helm docs to our charts

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1822]
@dejanzele had a nice readme generated for the armada-bundle. We should do the same for our other charts.

We should be able to use helm-docs for this.

**Comment by jwillker** [comment]
Hi @kannon92, I have opened a pr to solve this issue https://github.com/G-Research/armada/pull/1830

**Comment by kannon92** [comment]
https://github.com/G-Research/armada/pull/1830 resolves this issue.  Thank you @jwillker!
