### ISSUE TITLE
Add Python 3.9/3.10 suport

### ISSUE THREAD

**Issue by damelLP** [G-Research/armada#1861]
I'd like to be able to use the armada client in projects that use more recent versions of python.

Looking at the dependencies and the git history it wasn't immediately obvious to me why the upper bound constraint on the version of python was added. 

Is there a reason why not?

I think we could just remove it?

**Comment by kannon92** [comment]
Hello @damelLP!  Welcome to the armada project.

I think we pinned python version due to airflow.  Maybe 6 months ago we had issues with 3.9.  We can test and get it working now.  

For python client I think there is no issue.

**Comment by kannon92** [comment]
We pushed a new release to PyPi so you should be good to work with it now!

https://pypi.org/project/armada-client/
