### ISSUE TITLE
Event Ingester CRD and Install controller

### ISSUE THREAD

**Issue by richscott** [G-Research/armada#1904]
Using the Operator SDK (https://sdk.operatorframework.io/), write a spec (as Go struct definitions) for the run-time configuration of the Event Ingester, write controller logic to deploy the Event Ingester using Helm, and generate the CRD YAML definition.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1904?planning-poker) with Zenhub @richscott @kannon92 @dejanzele @suprjinx @Sharpz7

**Comment by richscott** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1904?planning-poker) with Zenhub @ClifHouck
