### ISSUE TITLE
Job Service CRD and Install Controller

### ISSUE THREAD

**Issue by richscott** [G-Research/armada#1905]
Using the Operator SDK (https://sdk.operatorframework.io/), write a spec (as Go struct definitions) for the run-time configuration of the Job Service, write controller logic to deploy the Job Service using Helm, and generate the CRD YAML definition.

**Comment by kannon92** [comment]
I just thought about this and I don't know if job service should be part of the operator.  We do deployment of this on our airflow kubernetes cluster and outside of armada actually.  

I believe we also removed it from our god docker image that releases all parts of Armada.  

I guess for the airflow team they could use the operator to just deploy the jobservice so maybe we should use it?

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1905?planning-poker) with Zenhub @richscott @kannon92 @dejanzele @suprjinx @Sharpz7

**Comment by kannon92** [comment]
@severinson and I discussed this.  I think the jobservice should not be included with the operator.  Currently job service is deployed outside of the central armada components.
