### ISSUE TITLE
Lookout CRD and Install Controller

### ISSUE THREAD

**Issue by richscott** [G-Research/armada#1907]
Using the Operator SDK (https://sdk.operatorframework.io/), write a spec (as Go struct definitions) for the run-time configuration of the Lookout  service, write controller logic to deploy the Lookout service using Helm, and generate the CRD YAML definition.

Also, write logic to run the data-model migration - Postgres schema creation, etc.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1907?planning-poker) with Zenhub @richscott @kannon92 @dejanzele @suprjinx @Sharpz7

**Comment by richscott** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1907?planning-poker) with Zenhub @ClifHouck
