### ISSUE TITLE
Consider integrating the Errcheck linter

### ISSUE THREAD

**Issue by Smaug123** [G-Research/armada#1911]
A little while back I found the issue that was fixed by https://github.com/G-Research/armada/pull/1735, and just now (by dint of complaining about Golang error handling on Hacker News) I learned of the existence of https://github.com/kisielk/errcheck, a linter to point out when you've forgotten to handle an error. I just ran errcheck on the Armada repo as of the commit before #1735, and it pointed out precisely that bug (among many other places where errors are silently dropped).

(Specific instructions for me were extremely simple, because I use Nix, but I presume it's also easy using standard Go tooling. For me, `nix-shell -p errcheck go` and then `cd armada && git checkout --hard 6239d744d8676aa798ddf5784dd08ace802974bc^ && errcheck ./...` was enough.)

I have no particular skin in this game, but wanted to suggest incorporating errcheck into the pipelines.

(I was also pointed to https://github.com/golangci/golangci-lint as an aggregation of lots of important linters.)

**Comment by kannon92** [comment]
Hey  @Smaug123, thanks for suggesting this valuable add to our linter tooling. We currently have golang-ci so it is possible to just add errcheck to our linter list.

The only work to do is to fix the warnings tge linter suggests.  What you be interested in contributing to Armada with this change?

**Comment by kannon92** [comment]
> Sorry, Golang is extremely not for me :P

No worries!
