### ISSUE TITLE
CI/CD for Operator

### ISSUE THREAD

**Issue by kannon92** [G-Research/armada#1940]
We should have github actions defined for our operator.  

1) Unit
2) Linting
3) Integration
4) Coverage
5) Publishing

All of these are similar to the work we are doing in Armada so one can use that as a template.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1940?planning-poker) with Zenhub @richscott @kannon92 @dejanzele @suprjinx @Sharpz7

**Comment by richscott** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1940?planning-poker) with Zenhub @ClifHouck

**Comment by kannon92** [comment]
I think I'll take this one and do 1-4. I think we can wait for publishing once we get farther along.

**Comment by dave-gantenbein** [comment]
Should this be multiple tickets?

**Comment by kannon92** [comment]
Yea I created this ticket as a placeholder to at least get CI added.  I figured any one of these steps goes a long way to getting started with it.  

We obviously shouldn't publish the operator docker images until we have a real operator.  Right now, we don't have any real code yet.  But we can at least add linting, coverage and tests now.  That way we don't get bad builds.

**Comment by kannon92** [comment]
We added coverage here: https://app.codecov.io/github/armadaproject/armada-operator/tree/main

It is low right now because we haven't had any real PRs merged yet.  But this should at least give us information if we are going in the right direction.  

I also added a lint job and unit/integration.  These was merged.  I will create a new ticket for publishing the images.
