### ISSUE TITLE
Broken jobs aren't flagged in useful way by `armadactl submit`

### ISSUE THREAD

**Issue by itamarst** [G-Research/armada#201]
### Example 1: Completely missing everything

If the JSON/YAML is completely broken, no job is submitted, but also no useful error is printed:

```shell
$ cat empty.json 
{}
$ ./bin/armadactl submit empty.json 
$ echo $?
0
```

I would've expected an error about missing fields, and a non-zero exit code.

### Example 2: Bad pod spec

If the pod spec is no good, the job is successfully submitted, and then it get stuck in a loop between `Leased` and `Queued` state:

```
$ ./bin/armadactl submit badpodspec.yaml 
Submitted job id: 01dqwxzkxfwrrfhmr4hvh5zw5a (set: job-set-2)
$ ./bin/armadactl watch job-set-2
Watching job set job-set-2
Oct 23 18:25:44 | Queued:   0, Leased:   0, Pending:   0, Running:   0, Succeeded:   0, Failed
:   0, Cancelled:   0 | event: *api.JobSubmittedEvent, job id: 01dqwxw5b06tqc909ebxd2029f    
Oct 23 18:25:44 | Queued:   1, Leased:   0, Pending:   0, Running:   0, Succeeded:   0, Failed
:   0, Cancelled:   0 | event: *api.JobQueuedEvent, job id: 01dqwxw5b06tqc909ebxd2029f       
Oct 23 18:25:46 | Queued:   0, Leased:   1, Pending:   0, Running:   0, Succeeded:   0, Failed
:   0, Cancelled:   0 | event: *api.JobLeasedEvent, job id: 01dqwxw5b06tqc909ebxd2029f       
Oct 23 18:27:46 | Queued:   1, Leased:   0, Pending:   0, Running:   0, Succeeded:   0, Failed
:   0, Cancelled:   0 | event: *api.JobLeaseExpiredEvent, job id: 01dqwxw5b06tqc909ebxd2029f 
Oct 23 18:27:46 | Queued:   0, Leased:   1, Pending:   0, Running:   0, Succeeded:   0, Failed
:   0, Cancelled:   0 | event: *api.JobLeasedEvent, job id: 01dqwxw5b06tqc909ebxd2029f 
```

Errors in the pod spec are quite likely to occur, and the debug cycle is difficult if I now have to dig deep into ... the logs somewhere, not sure where as a new user, to figure out what I did wrong.

A better experience would be to validate the pod spec upfront, e.g. have `armadactl` call `kubectl create --dry-run --validate` to get at least partial validation. There's also https://kubeval.instrumenta.dev/

**Comment by jankaspar** [comment]
Hi @itamarst, thanks, could you share the ` badpodspec.yaml`, please?
It could be also useful to run `./bin/armadactl watch job-set-2 --raw` it will print out all events so we will see what happened.

**Comment by itamarst** [comment]
```
jobs:
  - queue: test
    priority: 0
    jobSetId: job-set-2
    podSpec:
      terminationGracePeriodSeconds: 0
      restartPolicy: Never
      containers:
        - name: sleep
```

Re --raw, perhaps a "Debugging Problems" section in the docs would be good place to suggest that.

**Comment by JamesMurkin** [comment]
Much appreciated. This is definitely a bug in the Executor. It should fail the job if attempting to submit a Job that is considered invalid by Kubernetes.

This would break the loop you are seeing.

The case with validation is we can only do so much, for example the above is valid by kubectl create --dry-run --validate

We can add some validation to be inline with kubectl, but I am not sure we are going to write a new validator for PodSpec that goes beyond kubectl for now.

**Comment by itamarst** [comment]
`kubeval` might do better? Worth a quick check, at least.
