### ISSUE TITLE
Using subcharts to simplify deployment steps

### ISSUE THREAD

**Issue by stackedsax** [G-Research/armada#363]
I understand (or, at least, my assumption is) that we don't want to bake redis, prometheus or the cluster monitoring into the sever and executor charts because heavy users of Armada may very well have a standalone HA redis set up separately, and they might use a totally different monitoring technology.

However, I think we can follow the convention that we pull those pieces in as dependencies and then simple have an `enabled` value to turn those pieces off if the user doesn't need them.  This is how I've seen other charts strike the balance between providing a one-line `helm install` to start playing with their tool while allowing more advanced users the pleasure of turning off whatever they don't need.  

I'm really trying to get to that magic one-line install in the quickstart and deployment docs.  Happy to take this on and make it happen, but I wanted to check in to make sure the team thought it was a good idea.

**Comment by kannon92** [comment]
https://github.com/G-Research/armada/tree/master/deployment/armada-bundle

@dejanzele added this so I think this goes a long way with what you want.
