### ISSUE TITLE
Windows Container support

### ISSUE THREAD

**Issue by beingamarnath** [G-Research/armada#532]
Does Armada project also support/facilitate Windows Containers?

**Comment by jankaspar** [comment]
Armada supports any pod specification, so it should be possible to use it with Kubernetes cluster with windows nodes, and submit jobs with pod specs containing Windows containers.

**Comment by beingamarnath** [comment]
Thanks for the update

**Comment by stackedsax** [comment]
@beingamarnath Thanks for the interest!  Also curious where you're looking to deploy Armada -- we're interested to hear how other people want to use the project.
