### ISSUE TITLE
Make armadactl queue management more like kubectl

### ISSUE THREAD

**Issue by robertdavidsmith** [G-Research/armada#699]
armadactl create-queue replaces the queue if it already exists, including overwriting any security settings. This risks accidently relaxing permissions, and is not what you'd expect a create command to do.

The API CreateQueue method also used to do this, but that was fixed by https://github.com/G-Research/armada/commit/83e72494a10aeeffa897cb6747acc5569c7b1079

Suggest we make armadactl queue management more like kubectl.

Replace armadactl create-queue and delete-queue with 

armadactl create queue
armadactl replace queue
armadactl edit queue
armadactl delete queue
armadactl get queue

which behave more like the kubectl equivalent, including defining queues via yaml and/or json.

As much of the logic should be re-usable as possible, so we can extend to the management of other objects in future.

The old create-queue and delete-queue will need to be left there for a while, but should log a warning saying they're depreciated.

**Comment by stackedsax** [comment]
I agree, making it more familiar would be great.  I pointed this one out to @jgiannuzzi, but we also have a couple folks coming on in October who might be able to address this if Jonathan can't before then.

Thanks!

**Comment by steffnova** [comment]
@stackedsax and @robertdavidsmith,

I assume the purpose for these changes is to make commands to do one thing and one thing only.
Do we have a definition for `edit`, `get` and `replace` commands and what would expected behaviour be?
