### ISSUE TITLE
Lookout: Make annotations which are a CIFS path clickable

### ISSUE THREAD

**Issue by robertdavidsmith** [G-Research/armada#701]
Hi,

We have a mixed WIndows/Linux workflow currently. Users have a Windows workstation running Chrome, and some output is written to CIFS fileshares by the Linux jobs running on Armada/k8s.

Building on https://github.com/G-Research/armada/issues/700, it would be great if annotations that contain a CIFS path were clickable. 

It's not clear how to make this work given chrome security constraints. Electron, chrome plugins, or a windows url handler (https://docs.microsoft.com/en-us/windows/win32/search/-search-3x-wds-ph-install-registration) are possibilities. It would be great to discuss the design before anyone starts work on this.

Kind regards,

Rob

**Comment by kannon92** [comment]
Hello, @robertdavidsmith can you test this for your usecase?  

https://github.com/G-Research/armada/issues/700

What does a CIFS path look like?

**Comment by robertdavidsmith** [comment]
Hi @kannon92,

Ok thanks, I will test this.

CIFS (aka Windows fileshare) links can take either of these forms, and both work in Chrome

```
<a href="file://mywindowsfileserver/mywindowsshare">Example One<a/>
<a href="\\mywindowsfileserver\mywindowsshare">Example Two<a/>
```

The first one is basically a standard URL and should clearly by highlighted as a link. The 2nd one is a bit debatable, this syntax is not so widely used in the wider world. However highlighting these would be a big productivity win at GR, with minimal downside, so I'd probably do these too on balance.


Kind regards,

Rob

**Comment by robertdavidsmith** [comment]
I've tried it out. It worked great for https://github.com/, but it didn't recognize paths starting "file://" or "\\" as links.

There are some security implications of allowing file:// anyway, I will discuss internally tomorrow.

**Comment by kannon92** [comment]
Yea, that is not ideal.  I created a new issue and I'll pull it into our backlog.

**Comment by kannon92** [comment]
> There are some security implications of allowing file:// and \\ anyway, I will discuss internally tomorrow. Not supporting these is arguably a "security feature" not a bug.

Any updates @robertdavidsmith ?
