### ISSUE TITLE
Ensure armada permission checking is fully unit tested

### ISSUE THREAD

**Issue by robertdavidsmith** [G-Research/armada#702]
It would be great if someone could fully unit test the permission checks in https://github.com/G-Research/armada/blob/master/internal/armada/server/submit.go 

This has some coverage already (https://github.com/G-Research/armada/blob/master/internal/armada/server/submit_test.go), but not everything is covered. Given this code is security critical, it should have 100% unit test coverage.

**Comment by andrewpcone** [comment]
When `SubmitJobs` causes a queue to be created, that queue gets the groups of present principal, including the group `"everyone"`. As a result, anyone with the `permissions.SubmitJobs` can submit jobs to that queue.

I've committed code that excludes the `"everyone"` group from queue ownership.

Moreover, I am skeptical that the creating principal's groups should automatically have privileges on the new queue. The only thing that we know for sure is that the user themselves should have all privileges. I think it's reasonable (nay optimal) to require the user to grant other users/groups by subsequent API calls.

Thoughts @severinson ?
