### ISSUE TITLE
Lookout: jobsets view: truncate job set on the left, not the right

### ISSUE THREAD

**Issue by robertdavidsmith** [G-Research/armada#711]
Internally at GR, we often use long jobset names. In the lookout jobset table view, these often get truncated. Only the leftmost bit of the name is visible.

However, the rightmost bit is far more useful, so please can we show that instead.

(GR internal issue id ARMADA-538)

**Comment by robertdavidsmith** [comment]
Related to https://github.com/G-Research/armada/issues/750

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/711?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott
