### ISSUE TITLE
[Documentation] Developer guide for using kind is out of date

### ISSUE THREAD

**Issue by steffnova** [G-Research/armada#766]
Developer guide for running armada executors locally is out of date.

[Kind version](https://github.com/G-Research/armada/blob/8a2e87da9dfa74d08d4ccd90439ad3ac2e64ac63/docs/developer.md?plain=1#L38) that should be used should be updated. In quick start guide v0.10.0+ version is used.

These [commands](https://github.com/G-Research/armada/blob/8a2e87da9dfa74d08d4ccd90439ad3ac2e64ac63/docs/developer.md?plain=1#L59-L66) no longer work with kind version v0.10.0+

**Comment by d80tb7** [comment]
Hi,

just wondering if we need this?  My understanding is that Kind will, by default, write out the cluster config to your KUBECONFIG file ([link to relevant docs](https://kind.sigs.k8s.io/docs/user/quick-start/#interacting-with-your-cluster)) so we shouldn't have to export it separately. I tried this on my system and the existing doc seemed to work fine.  I'm quite new to both Kind and Armada though so it's quite possible I've missed something.

thanks,

Chris

**Comment by steffnova** [comment]
Hi @d80tb7 

I've updated the Kind on my side and indeed this is not needed. Since everything else was covered with your previous pull request, I'll close this one.
