### ISSUE TITLE
Make Armada consider the resource used by jobs on Cordoned nodes

### ISSUE THREAD

**Issue by robertdavidsmith** [G-Research/armada#817]
## Problem

If you cordon a node with jobs on it, Armada no longer considers those nodes as part of the total capacity of the cluster when requesting new resource.

This makes sense as the resource isn't available for use, however it can cause strange scheduling behaviour.

Such as when a single user is using the farm. If the amount of jobs the user has running on cordoned nodes > total resource available in the cluster. Armada won't schedule any more jobs onto the cluster, even when there are empty nodes.

## Replication

Get a cluster with nodes 1, 2, 3, where each node is the same amount of resource

Cordoned node 1

Queue many jobs. These will fill nodes 2 + 3.

Cordon nodes 2 + 3

Uncordon node 1

Observe that Armada won't send any more jobs to the newly uncordoned (empty) node.

This is because the amount of resource the user has running > all resource available to Armada. 

 

## Solution

When reporting the amount of resource available in the cluster. include the resource allocated to jobs on cordoned nodes.

Total resource on cluster = sum (resource on uncordoned nodes) + sum (resource allocated to jobs running cordoned nodes)

**Comment by theAntiYeti** [comment]
I'm not fully convinced the problem is here. The report from executor to server ignores resource on cordoned nodes, but it also ignores all pods running on cordoned nodes. There must be more to this.
