### ISSUE TITLE
Quickstart instructions for Mac OS X don't work

### ISSUE THREAD

**Issue by andrewpcone** [G-Research/armada#865]
Two problems:

- The syntax `brew cask install <x>` has been replaced with `brew install --cask <x>`, but the instructions use the former, so they don't wokr.
- You don't actually get the `docker` CLI executable unless you open `/Applications/Docker.app`, so that needs to be included explicitly

**Comment by dejanzele** [comment]
Retested again and it is working on OS X.

Here is a PR which updated quickstart docs - https://github.com/G-Research/armada/pull/957
