### ISSUE TITLE
Make quickstart guide work reliably on all platforms 

### ISSUE THREAD

**Issue by robertdavidsmith** [G-Research/armada#902]
There have been issues with the guide not working, due to things like changes the kind command line.

Ensure it works on all platforms, and add automated tests to keep it working.

Relevant issues/PRs:

https://github.com/G-Research/armada/issues/867
https://github.com/G-Research/armada/issues/865
https://github.com/G-Research/armada/issues/268
https://github.com/G-Research/armada/pull/866

**Comment by dejanzele** [comment]
This PR should fix issues - https://github.com/G-Research/armada/pull/957
