### ISSUE TITLE
Allow exact match on Jobs tab in Lookout

### ISSUE THREAD

**Issue by robertdavidsmith** [G-Research/armada#908]
Problem

If my queue name is a prefix of someone else's

 - Such as batch-andrews which is a prefix of batch-andrewsi

Then when I search job by my queue name, I get this other persons jobs.

 

Proposal

Could we implement some way to alleviate this, possibly allowing for exact match (with via UI option or quoting the string).

 - I.e "batch-andrews" would only give matches for batch-andrews queue because it is quoted so we use an exact match

@JamesMurkin has full context, suggest getting in touch with him before starting work

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/908?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by ClifHouck** [comment]
Closing this as #1665 addresses this issue. Opened #1679 to track drop-down work if want to go that route.
