### ISSUE TITLE
Allow showing full jobset in Lookout jobset table

### ISSUE THREAD

**Issue by robertdavidsmith** [G-Research/armada#909]
Currently, the jobset name gets truncated in the jobset table. We could do a few things to make it better:

Make table wider if job set names are longer, currently it only takes up a fraction of the page
Make column resizable
Make cell show full job set with scroll if a user clicks/double clicks

**Comment by robertdavidsmith** [comment]
Suggest we widen the scope of this ticket to "make columns in lookout resizable and re-orderable"

**Comment by rankindaveyg** [comment]
Ensure this also resolves #711

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/909?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott
