### ISSUE TITLE
Provide requested resources info in Lookout

### ISSUE THREAD

**Issue by robertdavidsmith** [G-Research/armada#910]
Display cpu/memory/gpu etc as columns (with filtering)

**Comment by kannon92** [comment]
Where do you want these columns?  

Just to be clear, you'd want this as part of the columns for jobs?

And what do you mean by filtering?

**Comment by robertdavidsmith** [comment]
Hi,

Yes these should be part of the jobs view. I’d put them on the far right for now..

You can currently filter columns by typing in a value just below the column header. This is what we mean by filtering.

Currently the only resource types are memory, cpu, ephemeral-storage,and nvidia.com/gpu. However more will almost certainly be added in future.

Thanks,

Rob

**Comment by kannon92** [comment]
Following up with @robertdavidsmith, each resource type should be a separate column in Jobs view.

**Comment by kannon92** [comment]
Similar to https://github.com/G-Research/armada/issues/1483, resources can be multi container.  It is not clear why we should display multiple containers in these columns?  

Unlike the previous issue though, these resources are of a fixed length so it could be possible to append columns depending on resources for each container.

**Comment by robertdavidsmith** [comment]
Suggest we just display the sum across all containers, this is generally what people care about, and is simpler.
