### ISSUE TITLE
Add instructions in the quickstart document for remote setup on master

### ISSUE THREAD

**Issue by dans77777** [G-Research/armada#913]

**Comment by dejanzele** [comment]
@dans77777 do we want to have an EC2 deployment (either via Terraform, Ansible or simple shell), or can we make a Helm chart which bundles & installs all of the components in a k8s cluster?

**Comment by dejanzele** [comment]
Here is a PR which adds an Armada Bundle helm chart - https://github.com/G-Research/armada/pull/962
