### ISSUE TITLE
Create dev container and get it published with instructions for VS Code on armadaproject.io

### ISSUE THREAD

**Issue by dave-gantenbein** [G-Research/armada#981]
Create dev container and get it published with instructions for VS Code on armadaproject.io

https://code.visualstudio.com/docs/remote/containers

We could also look into IntelliJ solutions. https://www.gitpod.io/

**Comment by rankindaveyg** [comment]
8

**Comment by dave-gantenbein** [comment]
Closing in favor of #1599
